feat: update content and descriptions for next Keto Release
ory/web pull request #157
Opened 2021-03-09 10:35 UTC by jfcurran

2021-03-09 10:37 UTC, jfcurran commented
working on:
- integration examples
  - Text for integration examples
  - Code samples

2021-03-09 13:40 UTC, zepatrik requested changes

2021-03-09 13:40 UTC, zepatrik commented on src/pages/keto.tsx
> +            Zanzibar. Take a global view of permissions management and scale on
Are you talking about the reader or Keto here? If it is Keto,
```suggestion
            Zanzibar. Takes a global view of permission management and scales on
```

2021-03-09 13:40 UTC, zepatrik commented on src/pages/keto.tsx
> +            Zanzibar. Take a global view of permissions management and scale on
same here

2021-03-09 13:40 UTC, zepatrik commented on src/pages/keto.tsx
> +            more.{' '}
```suggestion
            <a href="https://www.ory.sh/docs/keto">documentation</a> to learn
            more.
```

2021-03-09 13:40 UTC, zepatrik commented on src/pages/keto.tsx
> +\tconn, err := grpc.Dial("keto-read-api", grpc.WithInsecure())
```suggestion
\tconn, err := grpc.Dial("keto-read-api")
```

2021-03-09 13:46 UTC, jfcurran commented on src/pages/keto.tsx
> +            Zanzibar. Take a global view of permissions management and scale on
@jaredpreston 👀  wdyt?

2021-03-09 15:08 UTC, jfcurran commented
yea - thats the best approach I think

2021-03-09 16:10 UTC, jfcurran commented
> I would make the codebox scrollable with a max-height

While I agree that having component's height shift to either larger or smaller values is suboptimal, I think in keto.tsx's case, and generally codebox.tsx's case it is negligible. 

Here is why:
Since we are showcasing multiple languages within the codebox, across all products, all with varying length, setting a max-height would truncate most example codes. 
- this would cut away from the effect of completely seeing a code example without having to scroll
  - it is great to see code samples fully, being able to grasp what makes them special at a glance. this is especially true with the curl example that was added in this pr. 
- all though there is great disparity between the height of the codebox when switching tabs, somebody who _wants_ to look at the code, is happy with what the codebox does: showing the code completely

let me know what you think @aeneasr

2021-03-09 16:14 UTC, jfcurran commented
I made a slight change to the codebox anyways, and gave it a max height, so that we can decide on what is best - we can always revert the latest commit :D

2021-03-09 16:16 UTC, jfcurran commented on src/pages/keto.tsx
> +            Zanzibar. Take a global view of permissions management and scale on
from my understanding, this is correct @zepatrik - this text passage is speaking to the developer and is informing them how keto allows you take a global view of permissions and how it scales with your needs

2021-03-10 10:23 UTC, aeneasr commented on src/config.tsx
> +      'Authorization Server based on Google Zanzibar, providing RBAC, ABAC and ACL',
We end with a period everywhere else

```suggestion
      'Authorization Server based on Google Zanzibar, providing RBAC, ABAC and ACL.',
```

2021-03-10 10:23 UTC, aeneasr commented on src/config.tsx
> +      'Authorization Server based on Google Zanzibar, providing RBAC, ABAC and ACL',
The text here is not really true - we do not provide these APIs. You can implement them using Keto if you want, but it's not an RBAC server.

From GitHub:

> Global and consistent permission and authorization server with an easy and granular permission language and sub 10-millisecond latency. Based on Google Zanzibar. Ships gRPC and REST APIs. Written in Go.

2021-03-10 10:23 UTC, aeneasr commented on src/pages/keto.tsx
> +            Zanzibar. Take a global view of permissions management and scale on
I believe the original to be correct, you "Take a global view of".

2021-03-10 11:15 UTC, jfcurran reviewed
any input guys? :)

2021-03-10 11:15 UTC, jfcurran commented on src/pages/keto.tsx
> +            any system.
```suggestion
            {brandPrefix}Keto is a global and consistent permission & authorization server with an easy and granular permission language and sub 10-millisecond latency. It is based on Google Zanzibar, written in Go, and ships gRPC and REST APIs. Take a global view of permissions management and scale on any system.
```

2021-03-10 13:16 UTC, aeneasr commented on src/pages/keto.tsx
> +            any system.
That sounds very very weird. The first sentences are descriptive, the second imperative.

2021-03-10 13:23 UTC, zepatrik commented on src/pages/keto.tsx
> +            any system.
Yes I don't like this mix as well.

2021-03-12 12:24 UTC, aeneasr commented on src/pages/keto.tsx
> +            any system.
So what is up with this? WIll this be changed? Does it stay like this? Come on, let's get this stuff done. @jaredpreston please give your input.

2021-03-12 12:33 UTC, jaredpreston approved these changes
I would defer to the description that you prefer jere and mirror the description from Github as a first version. Developing a value proposition on it is too complicated right now and I would rather listen to what customers say about it and then adjust wording to reflect why they think it's valuable.

2021-03-12 13:11 UTC, jfcurran commented
lets use 
```
{brandPrefix}Keto is a global and consistent permission & authorization server with an easy and granular permission language and sub 10-millisecond latency. It is based on Google Zanzibar, written in Go, and ships gRPC and REST APIs.
```
then, and publish the changes?

2021-03-12 15:32 UTC, aeneasr commented
LGTM, good to merge?

2021-03-12 15:32 UTC, jfcurran reviewed
👀

2021-03-12 15:32 UTC, jfcurran commented on src/pages/keto.tsx
> +            any system.
```suggestion
{brandPrefix}Keto is a global and consistent permission & authorization server with an easy and granular permission language and sub 10-millisecond latency. It is based on Google Zanzibar, written in Go, and ships gRPC and REST APIs.
```

2021-03-12 15:32 UTC, jfcurran commented on src/pages/keto.tsx
> +            any system.
```suggestion
{brandPrefix}Keto is a global and consistent permission & authorization server with an easy and granular permission language and sub 10-millisecond latency. It is based on Google Zanzibar, written in Go, and ships gRPC and REST APIs.
```

2021-03-12 15:35 UTC, aeneasr commented on src/pages/keto.tsx
> +            any system.
👍

2021-03-12 15:35 UTC, aeneasr commented on src/pages/keto.tsx
> +            any system.
👍

2021-03-12 15:43 UTC, zepatrik approved these changes

2021-03-12 15:46 UTC, jfcurran commented
last question: links to docs point to `/keto/docs` right now, should we point to `/keto/docs/next` ?

2021-03-12 15:47 UTC, aeneasr commented
> last question: links to docs point to /keto/docs right now, should we point to /keto/docs/next ?

`/keto/docs` is ok!

2021-03-12 15:51 UTC, merged

2021-03-12 15:51 UTC, aeneasr commented
Thank you everyone

2021-03-24 17:02 UTC, jfcurran commented
closes #155