feat: minor content updates for index and oathkeeper
ory/web pull request #159
Opened 2021-03-17 09:44 UTC by jfcurran

2021-03-17 13:16 UTC, aeneasr approved these changes

2021-03-17 14:48 UTC, aeneasr commented
@tacurran please review

2021-03-18 09:33 UTC, zepatrik requested changes
Nice, like the way this is going :+1:

2021-03-18 09:33 UTC, zepatrik commented on src/components/footer.tsx
> +        href: '/kratos'
can we maybe keep the order here to see what actually changed? it is very hard to tell right now

2021-03-18 09:33 UTC, zepatrik commented on src/components/thin-project.module.css
> +}
```suggestion
}

```

2021-03-18 09:33 UTC, zepatrik commented on src/config.tsx
> +      'Configure how traffic interacts with your application. Authenticate and authorize all traffic, using Zero Trust / BeyondCorp as open source.',
```suggestion
      'Regulate what traffic interacts with your application. Authenticate and authorize all traffic, using Zero Trust / BeyondCorp as open source.',
```
The wording here seems a bit unprecise and inaccurate, this is just one idea.

2021-03-18 09:33 UTC, zepatrik commented on src/pages/index.tsx
> +            'You can rely on open source software that is built together in a world-wide community of developers. Peer reviewed, vetted by expert developers - tried and tested.'
I like the imperative more, also the other texts are imperative
```suggestion
            'Rely on open source software that is built together in a world-wide community of developers. Peer reviewed, vetted by expert developers - tried and tested.'
```

2021-03-18 09:33 UTC, zepatrik commented on src/pages/index.tsx
> +            'Work with what you’re doing. Easy ways to make tools, software, platforms and coding languages used by your business already work with Ory.'
The second sentence is quite cumbersome, it took me 5 reads to get it. Maybe change to a different verb than `make .................................................................................................... work`.
```suggestion
            'Work with what you’re doing. Ory enables integrations with tools, software, platforms and coding languages used by your business already.'
```

2021-03-18 09:33 UTC, zepatrik commented on src/pages/index.tsx
> +            'Work with what you’re doing. Easy ways to make tools, software, platforms and coding languages used by your business already work with Ory.'
Maybe "integreations"? :joy:

2021-03-18 09:33 UTC, zepatrik commented on src/pages/index.tsx
> +          title: 'Rely on open standards',
I like it, just some other idea:
```suggestion
          title: 'Build on open standards',
```
"Rely" sounds like you are depending on someone else, while "build" makes you the leader.

2021-04-23 08:20 UTC, aeneasr commented
What's the status of this?

2021-05-28 14:44 UTC, closed without merging