blog: keto article
ory/web pull request #166
Opened 2021-04-22 11:28 UTC by vinckr

Feel free to leave some comments if a change is necessary, or write me in Slack!

2021-04-22 13:45 UTC, zepatrik requested changes
Sorry for all the comments, I am a pretty bad text reviewer :sweat_smile:
Will work on improving that.

I really like it :+1: 
Just some details and formulations I found.

2021-04-22 13:45 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +unnoticeable and available at all times.
```suggestion
They also have to serve high numbers of users around the planet, while ideally being
unnoticed and available at all times.
```

2021-04-22 13:45 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +initiator are really allowed to perform that action.
```suggestion
table for instance, authorization checks should assure that the
initiator really is allowed to perform that action.
```
Task and action are the same thing here?

2021-04-22 13:45 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +provides the ID management system )
That would be a perfect fit here IMO.
```suggestion
It is important to not confuse this with authorization (is this person who they pretend to be?).
This question can be answered by [Ory Kratos](https://www.ory.sh/kratos/), which is a
fully fledged modern identity provider (management system?).
```

2021-04-22 13:45 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +are made, before even starting a quick search service, for example.
```suggestion
In sophisticated cloud systems this can mean that thousands of authorization checks
have to be made to serve a basic search response.
```

2021-04-22 13:45 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +times can range in the minutes. This is bothersome when searching for something,
```suggestion
times can add up to minutes. This is bothersome when searching for something,
```

2021-04-22 13:45 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +physical locations as you would need to achieve low latency worldwide.
```suggestion
Because of the required strict data duplication, a strongly consistent system can not achieve low latency worldwide.
```

2021-04-22 13:45 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +it will be unavailable until it is successful.
This is not really true, errors can be handled by strongly consistent systems as well.
```suggestion
the data you want to protect.
```

2021-04-22 13:45 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +The solution are version tokens called “Zookies”.
Google/zanzibar calls them zookie, we decided to call them snaptoken (snapshot token).
```suggestion
The solution is to use version snapshot tokens (short "snaptokens").  
```

2021-04-22 13:45 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +access to and the exact versions of the objects they used to have access to.
```suggestion
The basic idea is that all digital objects are versioned. Keto only answers `allow` if access to
this specific version is granted. After an ACL update is issued (grant or revoke permissions),
there is a short period until the update propagates. The snaptokens ensure that
the system only ever wrongly answers `allowed` if the permission on the requested version was previously granted.
This requires the application to store the snaptoken next to every object
version and provide it on every access check request.
In essence, Keto guarantees that an entity can only access objects they currently have
access to and the exact versions of the objects they used to have access to.
```

2021-04-22 13:45 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +`allow` for the old version as defined in your version token. But when newer
```suggestion
version, but then access was revoked to the object. During the propagation time the system can still answer
`allow` for the old version as defined by the snaptoken. But when newer
```

2021-04-22 13:45 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +in the design.
```suggestion
Currently snaptokens are not implemented in Ory Keto, but they have been considered
in the design and will be added soon.
```

2021-04-22 14:20 UTC, vinckr commented on src/pages/blog/keto-zanzibar-evolution.md
> +    and secure open source software in under 10 minutes.
Oh yea 😅

2021-04-22 14:21 UTC, vinckr commented on src/pages/blog/keto-zanzibar-evolution.md
> +## Introduction
you are right! I should write a small guide for the blogposts some time.

2021-04-22 14:39 UTC, vinckr commented on src/pages/blog/keto-zanzibar-evolution.md
> +- consistent.
Hm I added large scale, so everything is covered; 
but I like the adjectives better, that way its a sentence.

2021-04-22 14:40 UTC, vinckr commented on src/pages/blog/keto-zanzibar-evolution.md
> +At Ory, we knew we had to unlock this superpower as well!
🎉

2021-04-22 14:46 UTC, vinckr commented on src/pages/blog/keto-zanzibar-evolution.md
> +crucial it works for all possible patterns.
I like the second version, it introduces some Keto terminology!

2021-04-22 15:04 UTC, vinckr commented on src/pages/blog/keto-zanzibar-evolution.md
> +provides the ID management system )
Love it!

2021-04-22 15:04 UTC, vinckr commented on src/pages/blog/keto-zanzibar-evolution.md
> +are made, before even starting a quick search service, for example.
thousands 😮

2021-04-22 15:10 UTC, vinckr commented on src/pages/blog/keto-zanzibar-evolution.md
> +in the design.
™️

2021-04-22 15:19 UTC, vinckr reviewed
Thanks a lot for the review @zepatrik !
I have added most of your suggestions, very helpful!
Maybe @aeneasr or @tacurran want to read it before we merge?

2021-04-26 09:33 UTC, zepatrik requested changes
Love it :heart_eyes:

2021-04-26 09:33 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +later codenamed Zanzibar ( originally it was
```suggestion
later codenamed Zanzibar (originally it was
```

2021-04-26 09:33 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +).
Does this render properly? Check if the closing bracket really is moved to the next line by prettier

2021-04-26 09:33 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +"Spice" from the space saga “Dune” makes it possible to safely travel to other
Check that the quotes are consistent and render nicely.
```suggestion
"Spice" from the space saga "Dune" makes it possible to safely travel to other
```
or 
```suggestion
“Spice” from the space saga “Dune” makes it possible to safely travel to other
```

2021-04-26 09:33 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +In Ory Keto Access Control Lists (ACLs) contain information on
Is there a way to make this better readable?
```suggestion
In Ory Keto, Access Control Lists (ACLs) contain information on
```

2021-04-26 09:33 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +permissions for the whole folder of documents.
Just a small detail, but makes it more intuitive IMO
```suggestion
relation tuple. So ACLs can contain other ACLs, for example to define that a set
of users that can view a document is made up of the users that have been
granted rights to modify that specific document as well as those who have viewing
permissions for the whole folder of documents.
```

2021-04-26 09:33 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +identity management system?
```suggestion
identity management system.
```

2021-04-26 09:33 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +checks have to be made to serve a basic search response. f each of those checks
```suggestion
checks have to be made to serve a basic search response. If each of those checks
```

2021-04-26 09:33 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +more updates to a data item.
It is quite hard to get this short sentence right, but this is my proposal:
```suggestion
which simplified means that you will get the same response once all
updates are propagated.
```

2021-04-26 09:33 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +considered in the design and will be added soon.
I struggled last review to find a better sentence but now I found one I like more :wink: 
```suggestion
Currently snaptokens are not implemented in Ory Keto, but all the concepts have been
worked out and integrated into the design already. Actual consistency guarantees will be added soon.
```

2021-04-26 09:33 UTC, zepatrik commented on src/pages/blog/keto-zanzibar-evolution.md
> +  In the near future:
```suggestion
In the near future:
```

2021-04-26 10:29 UTC, tacurran requested changes

2021-04-26 10:29 UTC, tacurran commented on src/pages/blog/keto-zanzibar-evolution.md
> +    Authorize billions of requests securelx and consistent with low latency and
Authorize billions of requests, secure, consistent, low latency and

2021-04-26 10:29 UTC, tacurran commented on src/pages/blog/keto-zanzibar-evolution.md
> +    Low latency, consistent, open source access control system
Authorization, low latency, consistent, open source access control system

2021-04-26 10:29 UTC, tacurran commented on src/pages/blog/keto-zanzibar-evolution.md
> +- flexible,
- flexible; @vinckr use semicolon in list after colon

2021-04-26 10:29 UTC, tacurran commented on src/pages/blog/keto-zanzibar-evolution.md
> +great demand for such a solution.
great demand for an open source solution that is community vetted and transparent.  Ory uses Keto as part of the Ory Platform, a comprehensive security system designed to meet the needs of sophisticated application developers seeking to provide cloud identity and access management in low latency infrastructure at scale.

2021-04-26 10:30 UTC, tacurran commented
@vinckr  I added a few small changes in the review.  Please merge them and publish this.  We can write part two in a month.

2021-04-26 10:39 UTC, vinckr commented on src/pages/blog/keto-zanzibar-evolution.md
> +considered in the design and will be added soon.
Grand! I like it.

2021-04-26 10:40 UTC, vinckr commented on src/pages/blog/keto-zanzibar-evolution.md
> +more updates to a data item.
Its very simplified so I think its ok if its a little off :)

2021-04-26 10:47 UTC, vinckr commented on src/pages/blog/keto-zanzibar-evolution.md
> +).
Locally it renders nicely!

2021-04-26 11:10 UTC, merged