feat: canonical plugin
ory/web pull request #179
Opened 2021-04-29 19:30 UTC by vinckr

This adds a canonical link option for blog posts ect.

I put https://www.ory.sh as canonical base url. 

## Proposed changes

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2021-05-02 16:18 UTC, aeneasr requested changes

2021-05-02 16:18 UTC, aeneasr commented on gatsby-config.js
> +    },
@vinckr you have not tried this out, because this includes a syntax error which does not allow the website to start. Please, when you make changes, try them out. Make sure they work. Reviewing PRs is very time and focus intense and it is frustrating to review stuff that does not work because the person has not actually tried if it works. I would even consider it rude. [Other ecosystems](https://www.neowin.net/news/linux-bans-university-of-minnesota-for-sending-buggy-patches-in-the-name-of-research/) outright ban contributors and their associates when broken things are shipped.

2021-05-03 07:54 UTC, vinckr commented
Sorry about that. 
I tested it but then I split up the PRs into two, 
one with the plugin and the other one with the content. 

But I did not know it errors out when you dont use the optional field anywhere and it is not explicitly typed. 
I used the dummy data in this PR too to test it out, so that is why it worked for me.
I should have tested it as is.

I added the blogpost into this PR now, so it works with `npm run develop`.

2021-05-03 10:13 UTC, merged

2021-05-03 10:13 UTC, aeneasr commented
Thank you!