feat: youtube embedd component
ory/web pull request #241
Opened 2021-06-17 17:39 UTC by vinckr

## Related issue

## Proposed changes

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2021-06-18 09:29 UTC, vinckr commented
@jfcurran is going to add the Grid

2021-06-18 13:55 UTC, aeneasr requested changes
I assume this isn't the final version? Because, I mean...

<img width="1420" alt="Bildschirmfoto 2021-06-18 um 15 55 18" src="https://user-images.githubusercontent.com/3372410/122571991-9bce9b80-d04d-11eb-942c-8e3767dd7c07.png">

2021-06-18 14:11 UTC, vinckr commented
Too big? 

I thought about making it pop out from a CTA `Why Hydra` or similar, but for the release really big so its not to be missed.

2021-06-18 14:25 UTC, aeneasr commented
Yes, it is way too big, does not fit the flow of the website, and is lacking context. The video is great but I should at least know what I’m watching before I click it - so for example „Use Case Sainsbury‘s“ on the left and vid on the right or something.

2021-06-18 15:18 UTC, vinckr commented
Still fiddling a bit with the text, but how does it look?

2021-06-18 15:24 UTC, aeneasr commented
Better! I would probably put it below the mail list banner and above the easy integration. The layouts should then be switched so right left / left right / right left for a nice visual flow

2021-06-18 15:30 UTC, aeneasr approved these changes

2021-06-18 15:30 UTC, aeneasr commented on src/pages/hydra.tsx
> +        overline={'A proven solution'}
```suggestion
        overline={'Proven Scalability'}
```

2021-06-18 15:30 UTC, aeneasr commented on src/pages/hydra.tsx
> +          </>
Please no `<br>` tags, keep it all in one line and let the layout engine decide how to break the text.

```suggestion
            If you need a reliable open source solution Hydra is the right tool for the job. Watch the video to learn how Hydra powers Sainsbury's My ID, handling hundreds of users per second with ease.
          </>
```

2021-06-18 15:30 UTC, aeneasr commented on src/pages/hydra.tsx
> +        title={<>Millions of users? No problem</>}
```suggestion
        title={<>Scale to Millions</>}
```

2021-06-18 15:30 UTC, aeneasr commented on src/pages/hydra.tsx
> +            <br></br>Watch the video to learn how Hydra powers Sainsbury's My ID, handling hundreds of users per second with ease.
Try to avoid "If you need" and make things imperative and positive.

> Sainsbury's ... with millions of customers, serving hundreds of users per second. Replicate their success now: **link**

2021-06-18 15:30 UTC, aeneasr commented on src/pages/hydra.tsx
> +              Check out the docs
```suggestion
              Get started
```

2021-06-18 15:30 UTC, aeneasr commented on src/pages/hydra.tsx
> +            <Button to={'/docs/hydra/'} style={'link'} iconRight={ArrowRight}>
link to get started

2021-06-18 15:30 UTC, aeneasr requested changes
meant to request changes

2021-06-18 15:41 UTC, aeneasr commented on src/pages/hydra.tsx
> +        title={<>Millions of users? No problem</>}
We don't really use punctuation elsewhere :)

2021-06-18 15:41 UTC, aeneasr commented on src/pages/hydra.tsx
> +              Check out the docs
I think you might want to get started once you saw the video!

2021-06-18 15:43 UTC, aeneasr commented on src/pages/hydra.tsx
> +        overline={'A proven solution'}
Devs don't really like the word "solution". I think we have proven scalability because Sainsbury's has a lot of users. Therefore, that's a claim we can make here! For solution, it's not clear what it solves. The reader has to make the connection between million of users, the video.

Also, from an SEO perspective, "proven solution" says nothing. However, if I search for "scalable oauth2 server" then this might help!

2021-06-18 16:31 UTC, vinckr commented
thanks for the quick feedback :)
adressed your requested changes and also removed the `/` from Ory / Products, as its the only place where its written like that. 
Also added contraste, an adopter of hydra & oathkeeper

2021-06-20 13:41 UTC, aeneasr reviewed
Making it a bit leaner :)

2021-06-20 13:41 UTC, aeneasr commented on src/pages/hydra.tsx
> +            success now.
```suggestion
            Ory Hydra powers Sainsbury's My ID with millions of
            customers and serving hundreds of users per second.
```

2021-06-20 13:43 UTC, aeneasr commented on src/pages/hydra.tsx
> +            customers and serving hundreds of users per second.
```suggestion
            customers and serving hundreds of users per second.
            Watch the video to learn more!
```

2021-06-20 13:51 UTC, merged