feat: OS pages content
ory/web pull request #252
Opened 2021-06-23 13:38 UTC by vinckr

https://github.com/ory/web/pull/249 redone on web branch

The change from #248 had to be included for styling.
If that PR needs changes I can change it here accordingly, but the layout was important for both.

Read more about my reasons for these changes here: ory-corp/product#151 (comment)

2021-06-23 14:32 UTC, jfcurran reviewed
Hey @vinckr great stuff, please see my comments regarding the use of the grid - I think its important we remain consistent regarding how images and text are displayed. My presumption is this has to do with how headlines look: although your suggested change works great for index.tsx for example, I think its lacking on hydra.tsx or keto.tsx

2021-06-23 14:32 UTC, jfcurran commented on src/components/layouts/hero/hero.tsx
> +      <Grid lg={6} md={7} sm={12} xs={12} className={cn(pb32)}>
```suggestion
      <Grid lg={5} md={7} sm={12} xs={12} className={cn(pb32)}>
```
I see why this is intended to fill half of the available space, but I disagree with doing so, as this decreases space around the text too much. Leaving it at 5 gives the content room to breathe

2021-06-23 14:32 UTC, jfcurran commented on src/components/layouts/hero/hero.tsx
> +      <Grid lg={6} md={7} sm={12} xs={12} className={cn(pb32)}>
```suggestion
      <Grid lg={6} md={6} sm={12} xs={12} className={cn(pb32)}>
```

> I see why this is intended to fill half of the available space, but I disagree with doing so, as this decreases space around the text too much. Leaving it at 5 gives the content room to breathe

the same reasoning applies here, although there is less real estate to begin with. I believe a 6/6 split works best here, and images are still displayed at a reasonable size for big tablets / small laptops

2021-06-23 14:32 UTC, jfcurran commented on src/components/layouts/hero/hero.tsx
> +      <Grid lg={6} md={5} sm={12} xs={12}>
```suggestion
      <Grid lg={6} md={6} sm={12} xs={12}>
```
see my previous comment for reasoning behind this suggestion

2021-06-23 14:32 UTC, jfcurran commented on src/pages/hydra.tsx
> +    <IconWrapper color={'base-white'} icon={'CheckCircle'} size={'24'} />
😎 👍

2021-06-23 14:32 UTC, jfcurran commented on src/pages/keto.tsx
> +            ships gRPC and REST APIs.
great

2021-06-23 15:49 UTC, vinckr commented on src/components/layouts/hero/hero.tsx
> +      <Grid lg={6} md={5} sm={12} xs={12}>
```suggestion
      <Grid lg={7} md={6} sm={12} xs={12}>
```
lg has to be 7 right?

2021-06-24 11:54 UTC, jfcurran requested changes

2021-06-24 11:54 UTC, jfcurran commented on src/components/layouts/hero/hero.tsx
> +      <Grid lg={7} md={6} sm={12} xs={12}>
```suggestion
      <Grid lg={6} md={6} sm={12} xs={12}>
```
the grid props dont need to add up to `{12}`, but they should not exceed `{12}`

2021-06-24 12:38 UTC, vinckr commented
Should I make a separate PR for the hero text changes? I could just add the commit in here.

2021-06-24 13:09 UTC, jfcurran commented
lets merge this, and discuss the content changes in a different PR. I think it's good to add reviewers (if needed) in a specific PR :) 👍

2021-06-24 14:18 UTC, merged