feat: OS featurelist
ory/web pull request #261
Opened 2021-06-28 11:44 UTC by vinckr

Implementing the same featurelist from /pricing in the OS pages to show more detail on the capabilities of our OS projects. 
Currently only Hydra/Kratos as they are most straightforward, keto & oathkeeper are a bit harder.

- feat: kratos OS features
- feat: hydra OS features

2021-06-28 11:54 UTC, jfcurran commented
right off the bat, I think this is an amazing addition - very nice 🚀 
One comment from my side would be: I think adding links to certain topics with great depth (eg OAuth2) would greatly benefit readers. these links could point to respective doc pages or in case of OAuth2 maybe even their spec.

2021-06-28 11:54 UTC, jfcurran approved these changes
😎

2021-06-28 11:57 UTC, vinckr commented
Yes good point with the links!
I was debating (with myself) wether it would be good to add some or not.
Most links (except maybe OAuth2.0 spec) would lead to a ressource under ory.sh anyway... 
I will add some 😉

2021-06-28 12:16 UTC, aeneasr commented on src/pages/kratos.tsx
> +                title: 'Admin Management',
```suggestion
                title: 'User Management',
```

2021-06-28 12:16 UTC, aeneasr commented on src/pages/kratos.tsx
> +              },
Missing the UI stuff :)

2021-06-28 12:16 UTC, aeneasr commented on src/pages/hydra.tsx
> +                title: 'Flexible User Management',
Maybe more like "Integrates everywhere"?

2021-06-28 12:16 UTC, aeneasr commented on src/pages/hydra.tsx
> +              },
Something like "Bring your own UI" maybe?

2021-06-28 12:20 UTC, jfcurran commented
additional note:
lets seperate content from the components and pages, and create respective props how did for `quotes.tsx` and `adopters.tsx`. 
you can create a new file in the respective folder and call it `feature-list-content.tsx` - currently (with this PR in mind) `feature-list.tsx` is being used on `pricing.tsx`, ` kratos.tsx`and `hydra.tsx`. move feature-list's respective content into `feature-list-content.tsx` and simply pass the content to feature-list using something like `featurelistPricing ` `featureslistKratos` `featurelistHydra`. that way its a bit cleaner imo

2021-06-30 11:28 UTC, aeneasr requested changes
<img width="629" alt="Bildschirmfoto 2021-06-30 um 13 27 51" src="https://user-images.githubusercontent.com/3372410/123952974-00bbb700-d9a7-11eb-9c17-2f14fb8a56cf.png">

2021-07-02 08:35 UTC, aeneasr requested changes

2021-07-02 08:35 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +        Sign up now and instantly access these features. All features except the Ory CLI and user interfaces are included when self hosting.
This looks unformatted, can you please run `npm run format`?

2021-07-02 08:35 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +        Issue OAuth 2.0 Access, Refresh and ID tokens in a secure and efficient manner. Ory Hydra secures critical environments for billions of users.
```suggestion
        Issue OAuth 2.0 Access, Refresh and ID Tokens in a secure and efficient manner. Ory Hydra secures critical environments for billions of users.
```

2021-07-02 08:35 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +        Issue OAuth 2.0 Access, Refresh and ID tokens in a secure and efficient manner. Ory Hydra secures critical environments for billions of users.
There are two "secure" following one another, please avoid duplication. Generally, by-sentences like "efficient manner" add little information. Maybe it makes sense to rework this sentence:

```suggestion
        Ory Hydra is a hardened and certified OAuth 2.0 and OpenID Connect provider, securing hundreds of billions of API requests in thousands of deployments.
```

2021-07-02 08:35 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +            Use your own branding and user interfaces for all OAuth2.0 and OIDC flows. Ory Hydra lets you use your styles and flows powered by a REST API and intuitive CLI.
```suggestion
            Use your own branding and user interfaces for all OAuth2.0 and OpenID Connect (OIDC) flows. Ory Hydra lets you use your styles and flows powered by a REST API and intuitive CLI.
```

2021-07-02 08:35 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +            Migrate from <Button style={'link-inline'} to={'https://mitreid-connect.github.io/'}>MITREid Connect</Button> to Ory Hydra. Migration documentation is provided.
Where is the documentation?

2021-07-02 08:35 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +            Store cryptographic keys for e.g. signing JWTs securely and manage OAuth 2.0 clients directly from the CLI.
We are storing these encrypted which adds secuirty

2021-07-02 08:35 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +            Sleep easy, knowing that Ory Hydra is secured against attack vectors and scales as required. Ory Hydra serves tokens to millions of users weekly and just works.
So the correct terminology here would be:

- Reduce (security) incidents
- Reduce on-call pagers

or something like that :)

2021-07-02 08:35 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +        Control who can access what in your application. Ory Keto serves decisions at scale globally with low latency.
It doesn't really serve decisions, maybe like "answers" or something like that

2021-07-02 08:35 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +            Determine if a user is allowed to take an action with HTTP and gRPC APIs.
```suggestion
            Determine if an entity (user, service, IoT) is allowed to perform an action using HTTP or gRPC APIs.
```

2021-07-02 08:35 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +            title: 'Low Latency and Zero Downtime',
```suggestion
            title: 'Low Latency and Highly Available',
```

2021-07-02 08:35 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +              Delight users with a smooth experience and no downtime.
What is a smooth experience? Hit them with facts :)

```suggestion
              Zanzibar has maintained 95th-percentile latency of less than 10 milliseconds and availability of greater than 99.999% over 3 years of production use.
```

2021-07-02 08:35 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +            Integrate easily with your existing data structures. Ory Keto works with any kind of identifiers.
```suggestion
            Ory Keto integrates with any existing data structures and identifiers.
```

2021-07-02 09:19 UTC, jfcurran commented
waiting for our friend @github-actions to give us the 👀 **preview** ✨ 
looking great locally ♥️

2021-07-02 09:31 UTC, vinckr commented
Still need to make some changes.

2021-07-02 12:07 UTC, vinckr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +              Delight users with a smooth experience and no downtime.
How does this sound? 

Ory Keto is based on [Zanzibar](https://www.ory.sh/keto-zanzibar-evolution/), which has maintained 95th-percentile latency of less than 10 milliseconds and availability of greater than 99.999% over 3 years of production use.

2021-07-02 14:42 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +              Delight users with a smooth experience and no downtime.
Much better!

2021-07-02 14:43 UTC, aeneasr commented
If a PR is work in progress, mark it as "draft" and clear the reviewers. Once it's ready to be reviewed, unmark it as draft, and tag reviewers :)

2021-07-05 08:17 UTC, vinckr commented
@aeneasr 
ready now, only some minor changes to keto text were missing.

2021-07-05 08:18 UTC, jfcurran approved these changes

2021-07-05 08:40 UTC, aeneasr requested changes

2021-07-05 08:40 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +              partners, customers, etc...).
Please no `etc...` either do `item a, item b, etc.)` or `item a, item b, ...)` or `(e.g. employees, partners, customers)`

2021-07-05 08:42 UTC, aeneasr requested changes

2021-07-05 08:42 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +              favourite pet ect..) and create your own user interfaces for flows
typos

```suggestion
              favourite pet etc.) and create your own user interfaces for flows
```

2021-07-05 08:43 UTC, aeneasr commented
Please use grammarly to check your text for typos.

2021-07-05 10:00 UTC, aeneasr commented
There are still more typos so I'm guessing you'll be tagging me again once the PR is done

2021-07-05 14:09 UTC, aeneasr commented on src/components/layouts/featurelist/feature-list-content.tsx
> +              <i>Coming soon:</i> The next generation of Ory Oathkeeper. Learn
No `<i>` tags, please use `<em>` instead:

```suggestion
              <em>Coming soon:</em> The next generation of Ory Oathkeeper. Learn
```

2021-07-05 14:11 UTC, merged