feat: create page for job openings
ory/web pull request #266
Opened 2021-07-01 14:08 UTC by jfcurran

This pull-request is still in progress.

This PR aims to create a jobs page that contains the following:

- `hero.tsx` a hero with image
- `new` a list of job openings, generated using a graphQL query, listing out available job openings - with each opening being a markdown file that lives in ./jobs/job.md
  - .mds used for job openings must contain position, starting date, location/remote, and more (please add) `features.tsx`
- `features.tsx` a component that displays our company values in succinct and comprehensible fashion 
- `features.tsx` a component that displays four benefits of working for us
- `quotes.tsx` TBD a component featuring quotes from team members
- `faq.tsx` component with frequently asked questions
- `quickstart.tsx` a component that allows for contact. 
  - Are you looking for other ways to work with us? Get in touch!
- `footer.tsx`

2021-07-12 14:43 UTC, aeneasr commented
I have another PR with important changes that will cause a lot of conflicts. Can we get this merged? Otherwise I'll go ahead with the next changes.

2021-07-12 14:58 UTC, jfcurran commented
@vinckr This page is looking good for now - is the content final? if yes, please give it a pass and check for typos and alike, thank you. I didn't find any, but I saw the writing of Open Source and open source to be inconsistent

2021-07-12 15:17 UTC, aeneasr requested changes

2021-07-12 15:17 UTC, aeneasr commented on gatsby-node.js
> +    charlist = 's'
We reverted this, now it's back. Please revert it again.

2021-07-13 09:34 UTC, aeneasr requested changes

2021-07-13 09:34 UTC, aeneasr commented on gatsby-node.js
> +    charlist = '/s'
Cmon...

```suggestion
    charlist = '\s'
```

2021-07-13 09:34 UTC, aeneasr commented on src/components/layouts/features/features-content.tsx
> +  <IconWrapper color={'themed-primary'} icon={'ArrowRightBold'} size={'16'} />
We deprecated IconWrapper, please use `<i>`

2021-07-13 09:34 UTC, aeneasr commented
Please address the merge conflicts with blog-hero

2021-07-13 11:28 UTC, aeneasr commented on gatsby-node.js
> +    charlist = 's'
Dude, please, it's still not correct. Just accept this patch, please:

```suggestion
    charlist = '\s'
```

2021-07-13 11:30 UTC, merged

2021-07-13 11:32 UTC, aeneasr commented
Shipped 🎉 

![](https://media.giphy.com/media/Hw8vYF4DNRCKY/giphy.gif)

2021-07-13 11:42 UTC, jfcurran commented
this better not be the Ever Given
![image](https://user-images.githubusercontent.com/24988314/125445871-9ce8dca7-fb5f-44b4-9d55-5c55824d74cd.png)