feat: de-dupe jobs postings content
ory/web pull request #359
Opened 2021-09-17 16:42 UTC by zepatrik

Closes #357 

This is just one way to do it. You can alternatively also define the individual things in a separate `jobsContent.tsx`, import it, and then `map` it to the actual page. But let's look at this together on Monday :wink:

2021-09-17 18:49 UTC, jfcurran approved these changes
😎 nice @zepatrik - easy fix

2021-09-20 07:35 UTC, vinckr requested changes
We can use the `About` only for developer job openings right now due to the closing sentence.
Either we 
- use two (or more?) different versions of the About here 
- a different end sentence, or 
- rewrite the about section so that it does not contain any specifics about the jobs.

I think having a generic `About` section would work the best in the future ect.

WDYT?

2021-09-20 07:35 UTC, vinckr commented on src/markdown/jobs/sales.mdx
> +import { About, WorkAtOry } from './shared'
Here is a problem in that the Sales Development Representative is having a slightly different about section than the code heavy jobs:
They are not 
`working on one of the industry's most important code-bases`
they are 
`talking  to customers to understand their biggest problems and tailor solutions to solve them, having a positive
impact on hundreds of millions of people worldwide."


So we would need two different versions of the `About` here or just a different end sentence, or rewrite the about section so that it does not contain any specifics about the jobs.

2021-09-20 07:35 UTC, vinckr commented on src/markdown/jobs/shared.tsx
> +      industry's most important code-bases, having a positive impact on hundreds
```suggestion
      industry's most important code-bases, having a positive impact on hundreds
```
This sentence is problematic when we use a boilerplate `About` for all job openenings, since not everyone is working on codebase.

2021-09-20 12:21 UTC, aeneasr commented
Use this only for developers, and if we have multiple positions with the same description for sales introduce that pattern there also!

2021-10-04 15:28 UTC, aeneasr commented
What's needed to get this merged?

2021-10-04 15:31 UTC, zepatrik commented
This was just a POC for @vinckr and @jfcurran to get started.

2021-10-04 15:31 UTC, aeneasr commented
Ok, so we can close?

2021-10-04 16:02 UTC, vinckr commented
Should be ready to merge now, will update https://github.com/ory/web/pull/373, so it uses the same shorthands.

2021-10-04 19:41 UTC, merged