feat: google analytics with advanced consent
ory/web pull request #428
Opened 2021-11-16 22:56 UTC by MicLeey

<details>
  <summary>Desktop:</summary>
  
  ![2021-11-16_23-43](https://user-images.githubusercontent.com/15386836/142079351-4339ea44-286a-4c1a-8f22-9d3f48c53a88.png)
  
</details>

<details>
  <summary>Tablet:</summary>
  
  ![2021-11-16_23-43_1](https://user-images.githubusercontent.com/15386836/142079372-246f13d1-bdbf-44d7-9c27-8d4e31a28cee.png)

  
</details>

<details>
  <summary>Mobile:</summary>
  
  ![2021-11-16_23-44](https://user-images.githubusercontent.com/15386836/142079403-b37e16fa-07f3-43b9-895f-f3c6f1f8d3f8.png)

</details>

Blockers:
- Let me know if copy should be adjusted
- I don't know if we need to let users granuarly opt out of GA metrics
- We need a cookie policy for GDPR and PECR
- A privacy policy is required for CCPA

2021-11-17 08:18 UTC, BlueAcidFrog commented
FYI, I got an error message (google search console) describing a coverage problem: 

Coverage problems detected on community.ory.sh & ory.sh

To the owner of community.ory.sh:
There are 1 coverage type issues detected in Search Console for your website:
Main Error

Errors can prevent your page or feature from appearing in search results. The following errors were found on your website:
Sent URL is a soft 404 error.

We recommend that you fix these issues, if possible, so that your website provides the best possible experience and coverage in Google search.

2021-11-17 12:41 UTC, MicLeey commented
It is locked behind an `envIsProduction`. Do we have a variable for staging/netlify? I could add that.

Plausible and Matomo are being loaded as per usual as they are using cookieless mode. Nothing changed for those

2021-11-17 13:11 UTC, aeneasr commented
~I'm not sure, but I assume previes in netlify should set NODE_ENV to prod?~

> By default, Netlify’s buildbot sets NODE_ENV to development. You can change this value by setting a NODE_ENV environment variable.

https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-environment

Will this build with NODE_ENV=production? Or do we have some dev dependencies that are needed to build?

2021-11-17 13:14 UTC, MicLeey commented
It will - the same check is currently used to activate plausible in prod. Of course that means the actual GA tracking is untested. The banner works - screenshots in linked issue.

This is still blocked regardless, by a privacy/cookie policy for CCPA/GDPR respectively

2021-11-17 13:20 UTC, aeneasr commented
Got it, thanks! We should probably update:

https://github.com/ory/web/blob/44f7a9cf74be255701ae1396bb2bd0726f18878b/.github/workflows/publish.yml#L29

https://github.com/ory/web/blob/44f7a9cf74be255701ae1396bb2bd0726f18878b/.github/workflows/publish.yml#L84

and add `NODE_ENV=production` to both!

2021-12-07 11:29 UTC, aeneasr requested changes
A couple of to-dos:

1. [ ] Open incognito -> accept consent (reject all, accept all, ...) -> reload -> the banner shows up again
2. [ ] Missing CSP headers for gtag/ga/hubspot (see comment)
3. [ ] Ensure consent tracking works with ad blocker as well

Another question is that I believe we only load gtag and analytics but have all the categories enabled already. Do we need all of them?

2021-12-07 11:29 UTC, aeneasr commented on static/_headers
> +  Content-Security-Policy: default-src 'self' blob: 'unsafe-inline' 'unsafe-eval' unpkg.com *.algolianet.com *.algolianet.net storage.googleapis.com github.com *.githubusercontent.com gh-card.dev *.o
Wouldn't we need to allow-list all analytics URLs etc here also?

edit:// yes, we get CSP violations

2021-12-07 11:29 UTC, aeneasr commented on src/analytics.ts
> +  initializeTagManger(window, document, 'script', 'dataLayer', 'GTM-5JC2SVK')
@BlueAcidFrog can you please confirm that this ties into our existing GA account?

2021-12-07 11:29 UTC, aeneasr commented on src/analytics.ts
> +  Advertising = '5'
Does `Analytics`, `Enhancement`, `Basic` have an effect yet?

2021-12-07 11:40 UTC, BlueAcidFrog commented on src/analytics.ts
> +  initializeTagManger(window, document, 'script', 'dataLayer', 'GTM-5JC2SVK')
I can confirm the ID to be the correct one for Google Tag Manager (GTM-5JC2SVK). Ones we have set up GTM i can easily add GA Analytics to it.

2021-12-07 11:59 UTC, MicLeey commented on src/analytics.ts
> +  Advertising = '5'
Not yet, they just correspond the granular options given by the consent manager

2021-12-07 12:21 UTC, aeneasr commented on src/analytics.ts
> +  Advertising = '5'
I see, I assume those are then available in the tag manager for further processing?

2021-12-07 12:21 UTC, aeneasr commented on src/analytics.ts
> +  initializeTagManger(window, document, 'script', 'dataLayer', 'GTM-5JC2SVK')
Nice, ty

2021-12-07 14:15 UTC, aeneasr commented
@MicLeey i think we need to allow google analytics as well because gtag only adds the script which then loads google analytics

2021-12-07 15:10 UTC, merged