feat: update to /pricing
ory/web pull request #429
Opened 2021-11-17 15:32 UTC by jfcurran

- add more price tiers
- adjust css accordingly
- add modifiers to how prices are displayed, according to length or monetary value
- add additional themes 'themed' = primary color
- add prop fields 'asterik 1 & 2' to pricing/pricing.tsx to display important messages under pricing tiers

2021-11-18 09:17 UTC, BlueAcidFrog commented on src/page-content/pricing-tiers/pricing-cloud.tsx
> +        to: 'https://console.ory.sh/registration',
we will use Hubspot for this to track leads, they have a dedicated service for this.

2021-11-18 12:32 UTC, BlueAcidFrog commented on src/page-content/pricing-tiers/pricing-cloud.tsx
> +      price: '18',
```suggestion
      price: '21',
```

2021-11-18 19:48 UTC, aeneasr commented on src/page-content/pricing-tiers/pricing-cloud.tsx
> +        }
```suggestion
        },
        {
           icon: Plus,
           title: <>Fair use policy<span className={'is-themed-primary'}>***</span></>,
        },
```

2021-11-19 08:51 UTC, BlueAcidFrog commented on src/page-content/pricing-tiers/pricing-cloud.tsx
> +        to: 'https://console.ory.sh/registration',
```suggestion
        to: 'https://form.typeform.com/to/OCuquFBA#name=xxxxx',
```

2021-11-22 11:42 UTC, BlueAcidFrog commented
I can't implement the Hubspot formula until we get Analytics up and running. For now we use Typeform

2021-11-22 11:44 UTC, aeneasr commented
typeform is a good intermediate solution

2021-11-22 17:13 UTC, vinckr commented
Hey, should I do updates to the roadmap and features in this PR? @jfcurran

2021-11-23 08:48 UTC, aeneasr commented
Please don't forget the footnotes

2021-11-23 14:18 UTC, BlueAcidFrog commented on src/page-content/pricing-tiers/pricing-cloud.tsx
> +              title: <>Fair use policy<span className={'is-themed-primary'}>***</span></>,
please use footnotes on this too please

2021-11-23 14:19 UTC, BlueAcidFrog approved these changes

2021-11-23 22:13 UTC, BlueAcidFrog commented
> This pull request is being automatically deployed to Netlify.
> 
> 🔍 Inspect: https://app.netlify.com/sites/wonderful-sinoussi-8532a7/deploys/619d1083b5c9c321ad9e9d84 ✅ Preview: https://619d1083b5c9c321ad9e9d84--wonderful-sinoussi-8532a7.netlify.app

I can't agree with this version of the price plan design, I favor the previous one that is more simple in its design showing the basic features for each plan + additional features per plan. https://619d1083b5c9c321ad9e9d84--wonderful-sinoussi-8532a7.netlify.app

2021-11-24 10:12 UTC, BlueAcidFrog approved these changes

2021-11-24 10:12 UTC, BlueAcidFrog commented on src/page-content/content-pricing.tsx
> +      {notice: 'Content string with increased length'},
```suggestion
      {notice: 'If you regularly exceed the API rate limits or use a large number of high-impact requests we will need to ensure the sustainability of the system, including the right to upgrade your account'},
```

2021-11-24 11:13 UTC, jfcurran commented on src/page-content/pricing-tiers/pricing-cloud.tsx
> +        to: 'mailto:office@ory.sh',
@BlueAcidFrog is there a method that you prefer over simple mail?

2021-11-24 11:15 UTC, BlueAcidFrog commented on src/page-content/content-pricing.tsx
> +      {notice: 'If you regularly exceed the API rate limits or use a large number of high-impact requests we will need to ensure the sustainability of the system, including the right to upgrade your
```suggestion
      {notice: 'If you regularly exceed the API rate limits or use a large number of high-impact requests we will need to ensure the sustainability of the system, including the right to upgrade your account.'},
```

2021-11-24 11:15 UTC, BlueAcidFrog approved these changes

2021-11-24 11:37 UTC, aeneasr commented on src/page-content/pricing-tiers/pricing-cloud.tsx
> +        title: 'Sign up',
@BlueAcidFrog @jfcurran since this is currently a type form, "apply" would make more sense? We can use "Sign up" once we have the stripe integration shipped

2021-11-24 11:40 UTC, aeneasr commented
@BlueAcidFrog the forms need improvement.

1. The title still says "Apply for Ory Early Access"
<img width="369" alt="Bildschirmfoto 2021-11-24 um 12 39 07" src="https://user-images.githubusercontent.com/3372410/143231700-885b4044-d2df-42ad-b183-b6c323bb4c5a.png">
2. Success screen is always "Congrats, you are in line for a free Start Up plan! Our team will reach out to you to discuss the next steps." even though I applied for **growth**
3. Replace tech stack with use case, e.g.
   1. I want to migrate an existing auth system to Ory
   2. I am building a mobile app
   3. I am building a web app
   4. ...

2021-11-24 13:23 UTC, aeneasr commented on src/page-content/content-pricing.tsx
> +      {notice: 'If you regularly exceed the API rate limits or use a large number of high-impact requests we will need to ensure the sustainability of the system, including the right to upgrade your
```suggestion
      {notice: 'If you regularly exceed the API rate limits or use a large number of high-impact requests we will need to limit your maximum resource consumption to ensure the sustainability of the system.'},
```

2021-11-24 13:26 UTC, vinckr requested changes

2021-11-24 13:26 UTC, vinckr commented on src/page-content/pricing-tiers/pricing-cloud.tsx
> +        to: 'https://form.typeform.com/to/OCuquFBA#name=xxxxx'
```suggestion
        to: 'https://form.typeform.com/to/OCuquFBA#plan=start-up'
```

2021-11-24 13:26 UTC, vinckr commented on src/page-content/pricing-tiers/pricing-cloud.tsx
> +        to: 'https://form.typeform.com/to/OCuquFBA',
```suggestion
        to: 'https://form.typeform.com/to/OCuquFBA#plan=growth',
```

2021-11-24 13:49 UTC, vinckr commented
hey i fixed the typeform, it is not perfect, but we can merge 👍

2021-11-24 13:51 UTC, BlueAcidFrog commented
@vinckr thank you for this - we can update typeform any time after merged

2021-11-24 13:56 UTC, merged