feat: add datadetect adopters
ory/web pull request #46
Opened 2020-10-23 08:41 UTC by jfcurran

- adopters logo added

2020-10-23 08:41 UTC, jfcurran commented
link does not work with https

2020-10-23 10:16 UTC, zepatrik requested changes

2020-10-23 10:16 UTC, zepatrik commented on src/components/adopters.tsx
> +    url: 'http://datadetect.com/',
Then use e.g. 
```suggestion
    url: 'https://unifiedglobalarchiving.com/data-detect/',
```
but we really can't have non https links on our website.

2020-10-23 10:19 UTC, vinckr commented on src/components/adopters.tsx
> +    url: 'http://datadetect.com/',
ok I will talk to orly if that is good too. 
he told me to use the datadetect.com cause they might switch to a dedicated website for it

2020-10-23 10:19 UTC, vinckr commented
@jfcurran 
Also I cant see the logo in the preview? 
is that correct?

2020-10-23 10:22 UTC, zepatrik commented on src/components/adopters.tsx
> +    url: 'http://datadetect.com/',
ok but it won't help them now if we have the http URL there, they should add a redirect over https as well

2020-10-23 10:28 UTC, jfcurran commented
> @jfcurran
> Also I cant see the logo in the preview?
> is that correct?

Yes, this is correct. it is visible in our project pages

2020-10-23 13:03 UTC, vinckr commented
a https redirect will be added. will be soon probably..

2020-10-26 13:20 UTC, aeneasr commented
Is this ready for merge?

2020-10-26 13:22 UTC, jfcurran commented
> Is this ready for merge?

https:// has not been implemented yet - it is not ready yet.
@vinckr

2020-10-26 13:33 UTC, vinckr commented
He wanted to let me know when they implement the https redirect. 
If its not ready by tomorrow I will ask again. 

If its a problem to leave the PR open we can use https://unifiedglobalarchiving.com/data-detect/ in the meantime and then change, but I would rather do the correct URL right away

2020-10-26 13:42 UTC, vinckr commented
@aeneasr 
Ok I just talked to orly and we can merge with  ` url: 'https://unifiedglobalarchiving.com/data-detect/',`

He will let me know when they change the url, but it could take a little longer...

2020-10-26 14:33 UTC, zepatrik approved these changes

2020-10-26 15:39 UTC, merged