add: blog post on Ory Manifesto
ory/web pull request #465
Opened 2021-12-07 23:53 UTC by marneysof

may have some errors in formatting.

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2021-12-08 10:53 UTC, vinckr commented on src/markdown/blog/orymanifesto.mdx
> +##The Ory Manifesto
```suggestion
## The Ory Manifesto
```
Headlines are all broken, you need to leave a space and fix this for all headlines.

2021-12-08 10:54 UTC, vinckr requested changes

2021-12-08 10:54 UTC, vinckr commented on src/markdown/blog/orymanifesto.mdx
> +   A distillation of the key beliefs that underpin Ory as an organization.
Overline is too long

2021-12-08 12:22 UTC, jfcurran commented
Thank you @vinckr - it's good to keep an eye on these things

2021-12-09 08:24 UTC, BlueAcidFrog commented on src/markdown/blog/orymanifesto.mdx
> +## The Ory Manifesto
```suggestion
# The Ory Manifesto
```

2021-12-09 08:25 UTC, BlueAcidFrog commented on src/markdown/blog/orymanifesto.mdx
> +author: marneysof
```suggestion
author: Ory Team 
```

2021-12-09 08:25 UTC, BlueAcidFrog approved these changes

2021-12-09 08:26 UTC, BlueAcidFrog commented on src/markdown/blog/orymanifesto.mdx
> +author: marneysof
We should communicate our Ethos as if it comes from Ory, each and every one of us, like a unite.

2021-12-09 16:49 UTC, marneysof commented on src/markdown/blog/orymanifesto.mdx
> +author: The Ory Team
```suggestion
author: oryteam
```

2021-12-09 16:49 UTC, marneysof commented on src/markdown/blog/orymanifesto.mdx
> +author: The Ory Team
this is the accurate author.

2021-12-09 16:52 UTC, marneysof commented on src/markdown/blog/orymanifesto.mdx
> +## The Ory Manifesto
We already have an H1 as the title so everything in the blog post should be H2.

2021-12-14 22:55 UTC, aeneasr commented
Good to go?

2021-12-15 07:54 UTC, aeneasr commented
@vinckr @BlueAcidFrog

2021-12-15 07:59 UTC, BlueAcidFrog commented
Good to go!

2021-12-15 08:00 UTC, aeneasr approved these changes

2021-12-15 08:01 UTC, merged