feat: add Argon2 parameter blog post
ory/web pull request #48
Opened 2020-11-02 15:04 UTC by zepatrik

## Related issue
Blog post accompanying https://github.com/ory/kratos/issues/723 and https://github.com/ory/kratos/pull/803

2020-11-02 16:43 UTC, Bin-fluence reviewed
As instructed, I have added my comments and proposed suggestions directly to each line. Thanks Patrik!

**_Original Comment below:_**

Great Stuff @zepatrik!

Could we update the Title, description, headlines h1, h2 etc. to include some additional keywords? I have done a bit of research and besides repeating Argon2, I think these could be good:

Password hashing function
Password hashing
Cryptographic hashing algorithm
Cryptographic hashing function
Password hashing algorithm
Generate password hashes with Argon2
Secure password hashing algorithm
So as an example, maybe something like this?
Current title:
title>Choose Argon2 parameters following best practices - ory.sh</title>
Proposed title:
title> Set-up Argon2 for secure password hashing - ory.sh</title>
or
h1> How to configure Argon2's cryptographic hashing function - ory.sh<h1

I think repetition of some of these keywords will help drive SEO a lot.

Also maybe we could have h1> vary slightly from h2> as currently they are quite similar.

Great post, Patrik, let me know once its live, so that we can share on our social media and community channels.
Cheers,
JB

2020-11-02 16:43 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  Choose Argon2 parameters following best practices
```suggestion
  Set-up Argon2 for secure password hashing 
```

2020-11-02 16:43 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  Learn how to choose Argon2 parameters following best practices
```suggestion
  How to configure Argon2's cryptographic hashing function 
```

2020-11-02 16:43 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  Choose Argon2 parameters following best practices
```suggestion
  Set-up Argon2 for secure password hashing
```

2020-11-02 16:43 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  Learn how to choose Argon2 parameters following best practices
```suggestion
  How to configure Argon2's cryptographic hashing algorithm
```

2020-11-02 16:43 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +## Meet the Argon2 Parameters
```suggestion
## Meet the Argon2 cryptographic hashing Parameters
```

2020-11-02 16:43 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  This article sums up all the security best practices around Argon2 parameter
```suggestion
  This article sums up all the security best practices around Argon2's secure password hashing algorithm, specifically in regards to parameter
```

2020-11-02 16:49 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  Learn how to choose Argon2 parameters following best practices
Argon2 itself is the hashing function
What about
```suggestion
  How to configure the cryptographic hashing function Argon2 following best practices
```

2020-11-02 16:51 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  This article sums up all the security best practices around Argon2 parameter
Same here, argon2 is the hash function
```suggestion
    This article sums up all the security best practices around the Argon2 secure password hashing algorithm, specifically in regards to parameter
```

2020-11-03 07:41 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  Learn how to choose Argon2 parameters following best practices
LGTM.

2020-11-03 07:41 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  This article sums up all the security best practices around Argon2 parameter
LGTM.

2020-11-03 11:14 UTC, zepatrik commented
@vinckr you know that you can commit suggestions in one batch by going to the file changes tab?

2020-11-03 11:16 UTC, vinckr commented
> @vinckr you know that you can commit suggestions in one batch by going to the file changes tab?

I do now ;). 
I will read once more now and see if I can spot something.

2020-11-03 11:34 UTC, vinckr requested changes
minor formatting

2020-11-03 11:34 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  Set-up Argon2 for secure password hashing
Parameter is definitely a keyword for this blog post
```suggestion
  Determine Argon2 parameters for secure password hashing 
```

2020-11-03 11:34 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  Set-up Argon2 for secure password hashing
Parameter is definitely a keyword for this blog post

```suggestion
  Determine Argon2 parameters for secure password hashing
```

2020-11-03 11:34 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  How to configure Argon2's cryptographic hashing algorithm
Argon2 is the algorithm
```suggestion
  How to configure Argon2 parameters for cryptographic password hashing
```

2020-11-03 11:34 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  This article sums up all the security best practices around Argon2's secure password hashing algorithm, specifically in regards to parameter
Revert as this is wrong
```suggestion
  This article sums up all the security best practices around Argon2 parameter
```

2020-11-03 11:34 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +## Meet the Argon2 cryptographic hashing Parameters
I feel like these are two keywords too many, keep in mind that people still have to read this
```suggestion
## Meet the Argon2 Parameters
```

Also headings should have this weird casing, don't know the name
```suggestion
## Meet the Argon2 Cryptographic Hashing Parameters
```

2020-11-03 11:36 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +services storage.
This is genitive, as it is the storage of the service, please revert

2020-11-03 11:37 UTC, vinckr approved these changes

2020-11-03 11:44 UTC, vinckr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +services storage.
Tbh this is more a personal preference as I don't really like the possessive apostrophe.

2020-11-03 11:53 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +services storage.
Not sure about that, let's have a native speaker decide that.

2020-11-03 12:30 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  Set-up Argon2 for secure password hashing
LGTM

2020-11-03 12:30 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  Set-up Argon2 for secure password hashing
LGTM

2020-11-03 12:30 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  How to configure Argon2's cryptographic hashing algorithm
LGTM

2020-11-03 12:31 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +## Meet the Argon2 cryptographic hashing Parameters
LGTM

2020-11-03 12:32 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +services storage.
Personally, I would remove the apostrophe.😘

2020-11-03 12:38 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +## Meet the Argon2 cryptographic hashing Parameters
Guys which one? You both answered an **OR** question with :+1: :facepalm:

2020-11-03 12:41 UTC, Bin-fluence commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +## Meet the Argon2 cryptographic hashing Parameters
2nd one. Sorry.

2020-11-05 09:02 UTC, tacurran reviewed
Part 1 of feedback

2020-11-05 09:02 UTC, tacurran commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +
ADD
NB After yesterday's discussion with @zepatrik, this might not be in the scope...

By way of example, I first want to deconstruct a typical Argon2 hash and explain the contents.  To visualise the process, I wrote a very simple application (github.com/ory/oryworks/argon2ui.go or js) that has the following:

type credential struct {
	user string `json:"user"`
	pw string `json:"password"`
	salt string `json:"salt"`
}
type hashParams struct {
         iterations int `json:"iteration"`
         hlen string `json:"hashlength"`
         hashalgo string `json:"Argon2id"`
...
}

#funct main ()
h := patrikshashingfunction(using credential, hashParams)

return h

$argon2id$v=19$m=16,t=2,p=1$MHJ5S3JAdG9z$btlJ1wXz/hD81T6XZ9ZuPQ

hashalgo := argon2id
salt := v=19$m=16,t=2,p=1

2020-11-05 09:50 UTC, tacurran reviewed
Part 2

2020-11-05 09:50 UTC, tacurran commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +services' storage.
Consider 
even with full access to the system's' storage.
<even with full access to the services' storage.>

2020-11-05 09:50 UTC, tacurran commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +operation. This section is based on the
Consider
role in the on the hashing computation.
<impact on the hashing operation.>

2020-11-05 09:50 UTC, tacurran commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +   linearly dependent on this parameter. It allows you to increase the
Correction
The execution time is linearly correlated on the number of iterations

2020-11-05 09:50 UTC, tacurran commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +5. Key Length (i.e. Hash Length): This parameter depends on the intended usage.
Correction @zepatrik this is not clear
Key Length: This parameter defines the byte size in bits??? As such it defines the hash length in bytes and depends on the encoding method

2020-11-05 09:50 UTC, tacurran commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +   The authors say a value of 128 bits should be sufficient for most
ADD
The Argon2 algorithm authors claim ...

2020-11-05 09:50 UTC, tacurran commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +To reach the desired execution time, you have two variables to tweak. It is
CONSIDER
you can tweak two variables...

2020-11-05 09:50 UTC, tacurran commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +
ADD

## Conclusion
This article is purposely brief and aims to be an introduction and reference for developers that want to use the Argon2 password hashing algorithm.

2020-11-05 13:00 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +5. Key Length (i.e. Hash Length): This parameter depends on the intended usage.
It depends on the implementation. Some might use bits, others bytes. In general this is not fixed and as you said it also depends on the encoding. I would just not mention any unit there, as there is not a fixed one.

2020-11-05 13:08 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +---
I think we need to add that in the template, I tracked it as https://github.com/ory/web/issues/50

2020-11-11 10:42 UTC, aeneasr requested changes

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +path: '/argon2-parameter-choice-best-practice/'
```suggestion
path: '/choose-recommended-argon2-parameters-password-hashing/'
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  Determine Argon2 parameters for secure password hashing
```suggestion
  Choose Argon2 Parameters for Secure Password Hashing and Login
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  practices
```suggestion
  Pick recommended Argon2 (Argon2id, Argon2i) parameters (iteration, memory, parallelism) for secure login and password hashing, following security best practices using only open source.
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  Argon2 parameters for secure password hashing
```suggestion
  Recommended Argon2 Parameters for Secure Login and Protecting Passwords.
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  following security best practices
```suggestion
  Use open source to pick recommended Argon2 (Argon2id, Argon2i) parameters (iteration, memory, parallelism) and settings for secure login and password hashing.
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +  Security Best Practices
```suggestion
  Secure Password Hashing and Login
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +## What is Argon2?
```suggestion
## Arogn2 - Secure Login and Password Hashing
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +## Summary
Please avoid headlines following the hero section

```suggestion
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +[Argon2 specification paper](https://password-hashing.net/argon2-specs.pdf).
```suggestion
paper [Argon2: the memory-hard function for password hashing and other applications](https://password-hashing.net/argon2-specs.pdf).
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +1. Memory: The memory used by the algorithm. To make hash cracking more
```suggestion
1. **Memory**: The memory used by the algorithm. To make hash cracking more
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +2. Iterations: The number of iterations over the memory. The execution time
```suggestion
2. **Iterations**: The number of iterations over the memory. The execution time
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +3. Parallelism: The number of threads to use. This should be chosen as high as
```suggestion
3. **Parallelism**: The number of threads to use. This should be chosen as high as
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +4. Salt Length: The authors of Argon2 recommend this parameter to be 128 bits,
```suggestion
4. **Salt Length**: The authors of Argon2 recommend this parameter to be 128 bits,
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +5. Key Length (i.e. Hash Length): This parameter depends on the intended usage.
```suggestion
5. **Key Length** (i.e. Hash Length): This parameter depends on the intended usage.
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +## Meet the Argon2 Cryptographic Hashing Parameters
```suggestion
## Argon2's Cryptographic Password Hashing Parameters
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +## How to Choose the Parameter Values
```suggestion
## Choose the Right Argon2 Parameters
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +### Desired Execution Time
```suggestion
### Login Time Versus Security
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +### Adjust Memory and Iterations
```suggestion
### Adjust Memory and Iterations Parameters
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +## Automate it!
```suggestion
## Use Open Source to Choose Recommended Parameters
```

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +$ docker run -it --entrypoint kratos oryd/kratos:latest hashers argon2 calibrate 1s
Please fix the version here!

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +- [Calibration CLI Implementation in C# by @bburman](https://github.com/bburman/Twelve21.PasswordStorage)
We will be adding these sections as part of: https://github.com/ory/web/issues/5

2020-11-11 10:42 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +
```suggestion
## Conclusion

This article is purposely brief and aims to be an introduction and reference for developers that want to use the Argon2 password hashing algorithm for implementing secure login. Check out the [Ory Kratos](https://github.com/ory/kratos) open source project if you are looking for a login, registration, 2fa, profile management system where you can bring your own UI!
```

2020-11-11 10:47 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +$ docker run -it --entrypoint kratos oryd/kratos:latest hashers argon2 calibrate 1s
We did not release the CLI yet

2020-11-11 10:50 UTC, zepatrik commented
I feel like we have to find some process to do all the keyword/title/... related stuff more efficiently because everyone suggests other things and I am reiterating the exact same places the fourth time coming back to the original version in the end @Bin-fluence @vinckr @aeneasr 
Any ideas? Mine would be that only one person is responsible for that.

2020-11-11 10:58 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +### Desired Execution Time
The idea here was that the execution time is a (meta) parameter that you want to tweak. That's why it is under `## Choose the Right Argon2 Parameters`

2020-11-11 11:00 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +$ docker run -it --entrypoint kratos oryd/kratos:latest hashers argon2 calibrate 1s
Then this won't work with the latest tag either though?

2020-11-11 11:01 UTC, zepatrik commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +$ docker run -it --entrypoint kratos oryd/kratos:latest hashers argon2 calibrate 1s
Sure, I assumed we post this with the next release and fix the version here beforehand. Should have tracked it somewhere.

2020-11-11 11:01 UTC, aeneasr commented
Sorry about that, I did some keyword research and also have an idea what people are looking for (based on my own searches). Please use the proposed titles as they improve how people can find the article. Always avoid things like "summary" or "how it works" or "let's get started" in titles as these are SEO bad practices.

2020-11-11 11:02 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +$ docker run -it --entrypoint kratos oryd/kratos:latest hashers argon2 calibrate 1s
ok let's tag it as the next release, we can do the release today

2020-11-11 11:03 UTC, aeneasr commented on src/pages/blog/argon2-parameters-choice-best-practice.md
> +path: '/argon2-parameter-choice-best-practice/'
File name must also be updated

2020-11-11 11:16 UTC, aeneasr approved these changes

2020-11-11 11:17 UTC, aeneasr commented on src/pages/blog/choose-recommended-argon2-parameters-password-hashing.md
> +$ docker run -it --entrypoint kratos oryd/kratos:latest hashers argon2 calibrate 1s
```suggestion
$ docker run -it --entrypoint kratos oryd/kratos:v0.5 hashers argon2 calibrate 1s
```

2020-11-11 11:22 UTC, merged