docs: Review and update blogpost Hydra
ory/web pull request #49
Opened 2020-11-03 16:00 UTC by tacurran

## Checklist

- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have read the [security policy](../security/policy)
- [x ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added necessary documentation within the code base (if appropriate)

## Further comments

2020-11-04 10:53 UTC, aeneasr requested changes
Please remove the directories `.idea` and revert the changes to `package.json` and `package-lock.json`. You can remove things while keeping the local files using `git rm --cached .idea`. You should also add `.idea` to your [global gitignore](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c).

2020-11-09 10:35 UTC, aeneasr requested changes

2020-11-09 10:35 UTC, aeneasr commented on src/pages/blog/run-oauth2-server-open-source-api-security.md
>  # netstat -an | findstr /r "9000 9001 9010 9020"
Hashtag generally denote comments. I think the windows shell uses `>` as a shell indicator. So this should probably be:

```suggestion
> netstat -an | findstr /r "9000 9001 9010 9020"
```

2020-11-09 10:35 UTC, aeneasr commented on src/pages/blog/run-oauth2-server-open-source-api-security.md
>  # docker ps | findstr "hydra"
See comment above

2020-11-09 10:35 UTC, aeneasr commented on src/pages/blog/run-oauth2-server-open-source-api-security.md
> +Note 'netstat' on the MAC does not support all options used in Lunix and Windows. The 'lsof' command ($ man -k lsof) augments some of netstat missing functionality.
I assume these should be paragraphs? If so, please separate them with newlines:

````suggestion

For Linux

```shell
$ sudo ss -atuln | grep '9000\|9001\|9010\|9020'
```

For Apple MacOS (`/bin/bash` and `/bin/zsh`)
 
```shell
$ sudo netstat -atuln | grep '9000\|9001\|9010\|9020'
```

Note 'netstat' on the MAC does not support all options used in Lunix and Windows. The 'lsof' command ($ man -k lsof) augments some of netstat missing functionality.

````

2020-11-09 10:35 UTC, aeneasr commented on src/pages/blog/run-oauth2-server-open-source-api-security.md
> +The next section explains how to set up the PostgreSQL database system.
Newline code blocks for better readability:

````suggestion
The result will be something like:

```shell
641a26284ff2f8ee4580988371b91923d6711e20aa964ebbdf5b2e4b4f2592b8
```

The next section explains how to set up the PostgreSQL database system.
````

2020-11-09 10:35 UTC, aeneasr commented on src/pages/blog/run-oauth2-server-open-source-api-security.md
> +```shell
````suggestion

```shell
````

2020-11-09 10:35 UTC, aeneasr commented on src/pages/blog/run-oauth2-server-open-source-api-security.md
> +{"status":"ok"}
Wrap in codeblock:

````suggestion
```
{"status":"ok"}
```
````

2020-11-09 10:35 UTC, aeneasr commented on src/pages/blog/run-oauth2-server-open-source-api-security.md
> +Run and manage ORY Hydra
````suggestion
This command produces an overview of the CLI as follows:

```shell
Run and manage ORY Hydra
```

2020-11-11 15:54 UTC, tacurran commented
@aeneasr , I think if you merge this npm will update the package-lock automatically

2020-11-11 17:58 UTC, aeneasr commented on src/pages/blog/run-oauth2-server-open-source-api-security.md
>  # docker ps | findstr "hydra"
```suggestion
> docker ps | findstr "hydra"
```

2020-11-11 18:04 UTC, merged