Blogpost 'Securing Flask application using Ory Kratos and Ory Keto'
ory/web pull request #548
Opened 2022-01-31 19:40 UTC by gen1us2k

## Related Issue or Design Document

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-01-31 19:40 UTC, gen1us2k commented
@vinckr Could you please give some suggestions on how can I improve this blog post.

2022-01-31 21:28 UTC, vinckr requested changes
The content is looking good :tada:

I added a few comments, mostly some formatting.

2022-01-31 21:28 UTC, vinckr commented on src/markdown/blog/securing-flask-application-using-kratos-and-keto.mdx
> +3. It's better to use Ory Cloud instead of Open Source Kratos version
```suggestion
1. Get value of `ory_kratos_session` cookie and don't pass
2. Use Flask middleware and `ory/kratos` `keto` clients
3. It's better to use Ory Cloud instead of Open Source Kratos version
```

I think this last part can use a bit more detail. I am not sure what you mean by 1. and 2. and at 3. you should add something why you recommend using Ory Cloud (no docker setup required, gpdr, etc.)

2022-01-31 21:28 UTC, vinckr commented on src/markdown/blog/securing-flask-application-using-kratos-and-keto.mdx
> +overline: Securing flask application using Kratos and Keto
```suggestion
teaser: Securing your flask application using Kratos and Keto
subtitle: Let's build a flask application using Ory Kratos and Ory Keto
overline: Securing flask application using Kratos and Keto
```

This section could use a bit more variety. 
see the overline as a general category, maybe `flask authentication guide`
and in teaser something catchy for socials, e.g.  Securing your flask application with open source components or something like that.

2022-02-01 12:13 UTC, gen1us2k commented on src/markdown/blog/securing-flask-application-using-kratos-and-keto.mdx
> +overline: Securing flask application using Kratos and Keto
Done

2022-02-01 12:13 UTC, gen1us2k commented on src/markdown/blog/securing-flask-application-using-kratos-and-keto.mdx
> +3. It's better to use Ory Cloud instead of Open Source Kratos version
Made a better description.

2022-02-01 12:13 UTC, gen1us2k commented on src/markdown/blog/securing-flask-application-using-kratos-and-keto.mdx
> +- It can violate [GDPR](https://gdpr-info.eu/), [HIPAA](https://www.cdc.gov/phlp/publications/topic/hipaa.html#:~:text=The%20Health%20Insurance%20Portability%20and,the%20patient's%20consent%20or%20kn
Added more context

2022-02-01 14:27 UTC, gen1us2k commented
https://github.com/ory/web/pull/549 I created a new PR. Closing this one

2022-02-01 14:27 UTC, closed without merging