Added new blogpost 'Securing flask applications using Kratos and Keto'
ory/web pull request #549
Opened 2022-02-01 14:26 UTC by gen1us2k

## Related Issue or Design Document

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-02-01 17:32 UTC, vinckr requested changes
Looking good now, 

a few minor style things, then its good to go IMO.

2022-02-03 12:28 UTC, vinckr commented on src/markdown/blog/securing-flask-application-using-kratos-and-keto.mdx
> +In this article, I'll show you an example of how to add everything we need for the user's authentication without writing lots of lines of code. The code used in this blog post is available on [GitHub
```suggestion
In this article, I'll show you an example of how to add everything we need for the user's authentication without writing lots of lines of code. The code used in this blog post is available on [GitHub](https://github.com/gen1us2k/kratos_flask_example). We'll use [Flask](https://flask.palletsprojects.com/en/2.0.x/), [flask cookie-cutter](https://github.com/cookiecutter-flask/cookiecutter-flask), [docker](https://www.docker.com/), [docker-compose](https://docs.docker.com/compose/), [Postgres](https://www.postgresql.org/), [Ory Kratos](https://github.com/ory/kratos) and [Ory Keto](https://github.com/ory/keto).
```

2022-02-03 15:18 UTC, vinckr submitted a review, later dismissed
Lets go 🎉

2022-02-03 17:47 UTC, vinckr commented
@zeropaper 
Can we merge 🙏

2022-02-03 17:57 UTC, zeropaper approved these changes
Minor changes (sorry :) )

2022-02-03 17:57 UTC, zeropaper commented on src/markdown/blog/securing-flask-application-using-kratos-and-keto.mdx
> +[![](https://mermaid.ink/img/pako:eNptkktOIzEQhq9S8iojMSIShIUXSIjHCM2CRZRdS1CyK2kraVeP7RYKCGkuMIs5AbsR7DgTJ-AIlNsN0ZB4U9Xu7__rId8rw5aUVpF-deQNnTlcBGwqD3JaDMkZ16JP0EUKgBFmEiOM3h7_Pr3-_vP2-O9F0uch_batW
A detail... but... it would be good (also for SEO) to have an "alt" attribute something like `[![diagram of...](https://mermai...`

2022-02-03 17:57 UTC, zeropaper commented on src/components/freestanding/utils/codefromremote.tsx
> +      return 'yml' // FIXME: That's just workaround
Would be nice to know what the workaround is for... (in the code)

2022-02-03 17:57 UTC, zeropaper commented on src/page-content/content-blog.json
> +      "url": "http://github.com/aeneasr"
Glad you caught and corrected those spaces in the URLs... I recently noticed a similar issue (fixed since)... :+1:

2022-02-03 18:03 UTC, zeropaper commented
@vinckr I will merge it tomorrow early. There's something a bit weird about the GH actions (preview deployment) that I find a bit strange and want to a look at...

@gen1us2k I'm curious about the way you created that PR (nothing wrong), I'll ping you tomorrow :)

2022-02-03 18:03 UTC, gen1us2k commented on src/components/freestanding/utils/codefromremote.tsx
> +      return 'yml' // FIXME: That's just workaround
I added comments

2022-02-03 18:06 UTC, gen1us2k commented
@zeropaper I just wanted to have the experience to write blog posts using mdx files. I'll try to use CMS later to give feedback to you about my experience using it.

2022-02-03 18:06 UTC, vinckr commented
Perfect, thanks for taking a good look at it and for the fast response 🙏

2022-02-03 18:07 UTC, zeropaper commented
@gen1us2k it totally make sense to use your favorite editor

catch you tomorrow!

Over and out :)

2022-02-04 05:20 UTC, zeropaper approved these changes

2022-02-04 05:25 UTC, zeropaper commented
Thanks for the changes @gen1us2k!
I suspect that some CI isn't working as expected because the PR comes from a fork...

I'm merging now.

2022-02-04 05:27 UTC, merged