Patch 3
ory/web pull request #554
Opened 2022-02-08 12:33 UTC by RinorG

Customers will be directed to a Hubspot form first before they get to the console.

2022-02-08 14:40 UTC, BlueAcidFrog commented
<img width="1085" alt="Screenshot 2022-02-08 at 12 33 14" src="https://user-images.githubusercontent.com/89905002/153009503-5f26a129-e9a8-4ffe-9d8a-d1dbfcbed08c.png">

@jfcurran , @vinckr

2022-02-08 19:55 UTC, vinckr approved these changes
I feel it would be better to have less friction signing up, 
but otherwise LGTM 👍

2022-02-08 21:50 UTC, aeneasr requested changes
Hello, please let us discuss this before we merge this

2022-02-14 19:55 UTC, aeneasr commented
Closing as discussed

2022-02-14 19:55 UTC, closed without merging