fix: flutter authentication blogpost
ory/web pull request #558
Opened 2022-02-14 10:09 UTC by vinckr

2022-02-14 13:32 UTC, vinckr commented
@lucaIaconelli 

Here is your blogpost 🎉 
Feel free to review it before we merge.

2022-02-14 14:27 UTC, LucaIaconelli commented
Hey @vinckr 

Thanks it looks very cool.

Maybe if there was also the possibility to include it in the features for a few days it would be fantastic.

Thank you and I hope that the collaboration between IGLU and Ory will continue over time. (If you need Flutter resources, we have the best).

2022-02-14 14:38 UTC, vinckr commented
For sure, I always forget we have this new "featured" feature now 😁 .

2022-02-14 14:39 UTC, vinckr commented
@zeropaper 
@BlueAcidFrog 
This is done from our side, can you please review and merge 🙏 
Ping me if anything should be changed.

2022-02-16 11:28 UTC, BlueAcidFrog commented on src/markdown/blog/login-flutter-authentication-example-api-open-source.mdx
> +    login, auth, authentication, registration, flutter, dart, mobile, ios, android, mobile authentication, open source, ory, ory kratos
```suggestion
    login, password recovery, account verification, auth, authentication, registration, flutter, dart, mobile, ios, android, mobile authentication, open source, ory, ory kratos
```

2022-02-16 11:30 UTC, BlueAcidFrog requested changes
A couple of relevant keywords to be added please

2022-02-16 11:38 UTC, vinckr commented
thanks,
done.

2022-02-16 13:29 UTC, BlueAcidFrog approved these changes

2022-02-17 08:10 UTC, zeropaper approved these changes
@BlueAcidFrog It looks OK to me too.

Should I merge? (BTW, Do you have the access rights to merge?)

2022-02-17 08:28 UTC, vinckr commented
@zeropaper 
@BlueAcidFrog 
please merge 🙏

2022-02-17 08:31 UTC, merged