fix: Same CTA description
ory/web pull request #578
Opened 2022-02-28 12:55 UTC by BlueAcidFrog

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-02-28 14:10 UTC, vinckr requested changes
I left some comments. 
In general this looks good, a few things have to be fixed.

2022-02-28 14:10 UTC, vinckr commented on src/page-content/content-cloud.tsx
> +      <span className={'is-themed-primary'}> Ory Cloud </span> uses idustry standards
```suggestion
      <span className={'is-themed-primary'}> Ory Cloud </span> uses industry standards
```

2022-02-28 14:10 UTC, vinckr commented on src/page-content/content-cloud.tsx
> +      Ory Cloud is API-first, customizable, privacy conform and secure and deploys all Ory services in concert - at any scale, across the globe.
```suggestion
      Ory Cloud is API-first, customizable, privacy conform, secure, and deploys all Ory services - at any scale, across the globe.
```

not sure what is meant by `in concert`

2022-02-28 14:10 UTC, vinckr commented on src/page-content/content-cloud.tsx
> +      programming language.
```suggestion
      programming language.
```

2022-02-28 14:10 UTC, vinckr commented on src/page-content/navigation/header.json
> +          "description": "Start Free",
```suggestion
          "description": "Start Free",
```

you know my opinion on this.
keep  "No credit card required" 😁

2022-02-28 14:10 UTC, vinckr commented on src/page-content/navigation/header.json
> +          "description": "Ory builds open software",
```suggestion
          "description": "Ory builds open software",
```

free as in freedom not "for free" ! 
people want to pay us, they just want the freedom to modify things

2022-02-28 14:10 UTC, vinckr commented on src/page-content/navigation/header.json
> +          "description": "Open Source Documentation",
```suggestion
          "description": "Open Source Documentation",
```

This is also the documentation for Ory Cloud! 
Revert this as it is misleading IMO.

2022-02-28 14:10 UTC, vinckr commented on src/page-content/navigation/header.json
> +          "description": "Be part of Ory Community",
```suggestion
          "description": "Be part of the Ory Community",
```

"Sei ein Teil der Gemeinschaft"
vs.
"Sei ein Teil Gemeinschaft"

🤔

2022-02-28 14:10 UTC, vinckr commented on src/page-content/navigation/navigation-announcement.tsx
> +  shortText: 'Ory Cloud Start Up Plan!',
```suggestion
  shortText: 'Ory Cloud free for a year!',
```

sounds more exciting ;-)

2022-02-28 14:10 UTC, vinckr commented on src/page-content/navigation/header.json
> +          "title": "Global Authorization",
```suggestion
          "title": "Global Authorization Service",
```

What do you think of this? was patricks suggestion.

"Global Authorization" is a bit vague, that could mean anything from KYC to bodyguard services.

2022-02-28 14:42 UTC, BlueAcidFrog commented on src/page-content/navigation/header.json
> +          "description": "Ory builds open software",
```suggestion
          "description": "Ory builds free and open software",
```

2022-03-25 14:13 UTC, vinckr requested changes
This has some conflicts, it is probably if you copy the changes from here and make a fresh PR @BlueAcidFrog.

If this is not meant to be merged, please close.

2022-03-28 08:00 UTC, BlueAcidFrog commented
This can be merged! @vinckr

2022-03-28 08:55 UTC, vinckr commented on src/page-content/navigation/navigation-announcement.tsx
> +const jobs: AnnouncementProps =
```suggestion
const jobs: AnnouncementProps = {
```

2022-03-28 10:34 UTC, vinckr approved these changes

2022-03-28 10:34 UTC, merged