feat: authentication in the modern stack
ory/web pull request #586
Opened 2022-03-03 18:13 UTC by Benehiko

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-03-03 21:19 UTC, jfcurran commented
cool 👀 excited for more

2022-03-14 13:29 UTC, Benehiko commented
I just need to get the diagrams to look more like Ory, but other than that I think this is almost good to go. Let me know what you guys think :)

2022-03-14 13:31 UTC, Benehiko commented
I also think we will need to convert this markdown table into an image, because it breaks the scaling on mobile

![image](https://user-images.githubusercontent.com/18033717/158181938-bb82a7f1-b771-473d-b130-c6f82bde7548.png)
![image](https://user-images.githubusercontent.com/18033717/158182070-ae8cd33d-fef0-452c-81d9-e46132d6d0a8.png)

2022-03-14 18:29 UTC, vinckr requested changes
First of, I love this kind of content, we need more of it 😁

Biggest request i have to not use "auth" and always spell out if we mean authentication or authorization. If you want to include both maybe "identity management? 
I made a lot of comments but they are mostly about the auth thing and capitalization and a few sections that confused me a bit as well as some minor stylistic improvements. 

Great article, we should push it a bit when released 📈

2022-03-14 18:29 UTC, vinckr commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +utilizes the Operating System to render the User Interface (UI).
```suggestion
Applications that run on Android, iOS, desktop and server are all forms of
native applications. These applications usually provide native performance and
utilizes the operating system to render the user interface (UI).
```
Why the capitalization?

2022-03-14 18:29 UTC, vinckr commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +vulnerability accidentally leaking the session.
```suggestion
vulnerability leaking the session.
```

it wouldn't leak it on purpose in any case right?

2022-03-14 18:29 UTC, vinckr commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +There is no silver bullet in security that will fix all of our problems. But by
```suggestion
There is no silver bullet in security that will fix all of our problems. By
```

2022-03-14 18:29 UTC, vinckr commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +Application**.
```suggestion
(httpOnly) when **using a browser** and tokens when **using a native
application**.
```

2022-03-15 10:40 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +_most secure_ way of implementing Auth. Is it using Tokens such as JWTs?
Also `Auth` is used intentionally here. Due to the definitions that follow. Auth spawns AuthN and AuthZ

2022-03-15 10:43 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +If you are already familiar with Authentication, Authorization and Sessions you
I guess so :sweat_smile:

2022-03-15 10:44 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +Before we go any further with this article we first need to clarify what Auth we
I think the usage of `Auth` here is valid. Lots of people and blogs / companies use Auth as a broad term for AuthN and AuthZ. That's why people also get confused by which `Auth` they should be using or how this fits in. It's intentional since we define it just after this

2022-03-15 10:51 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +possible. This gives us the ability to maintain the software, add new features
I will change this part a bit

2022-03-15 10:53 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +utilizes the Operating System to render the User Interface (UI).
habbit :p

2022-03-15 10:54 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +utilizes the Operating System to render the User Interface (UI).
Also i think here Desktop, Server and Native Application might be capital here

2022-03-15 11:04 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +access the secret (session value). On top of this **we are then responsible** to
Yest the secret is the replacement for the user's credentials which we now store inside the session (JWT, cookie etc). But the session can be stored in different places, browser local storage, session storage or cookie storage. ofc cookie storage implies the usage of cookies.

2022-03-15 11:04 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +access the secret (session value). On top of this **we are then responsible** to
I think we might need a diagram depicting this

2022-03-15 11:08 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +disk since, hopefully, your server does not restart every couple of hours ;)
nice!

2022-03-15 11:19 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +Each technology behaves differently in their respective contexts and thus
hmm i think `thus` is required here :thinking:

2022-03-15 17:33 UTC, vinckr approved these changes
LGTM 🎉 
love the new diagrams too!

2022-03-23 10:38 UTC, vinckr approved these changes
looks great

2022-03-24 11:27 UTC, Benehiko commented
This can most likely be merged now. @vinckr @jfcurran you can hit the merge button if you are satisfied

2022-03-24 11:55 UTC, jfcurran submitted a review, later dismissed
fantastic

2022-03-24 11:56 UTC, jfcurran commented on src/markdown/blog/auth-and-modern-software.mdx
> +resource .
```suggestion
resource.
```

2022-03-24 12:05 UTC, jfcurran approved these changes
👍

2022-03-24 12:11 UTC, merged