fix: frontend part of supabase blog post
ory/web pull request #598
Opened 2022-03-18 11:26 UTC by gen1us2k

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-03-25 13:59 UTC, vinckr reviewed
Looks great already, 

I left some comments on the content, what you could add to make it more informative and exciting. 
There are some small typos, but we can fix them in the last review. 

I already got positive comments on the first part, so when completed we can polish it a little bit and then we have our first series "completed" 🎉

2022-03-25 13:59 UTC, vinckr commented on src/markdown/blog/building-url-shortener-using-clond-services-frontend.mdx
> +
Use the same format with list as here please:
https://github.com/ory/web/blob/master/src/markdown/blog/tutorial-url-shortener-supabase-ory-integration.mdx#what-we-will-use

2022-03-25 13:59 UTC, vinckr commented on src/markdown/blog/building-url-shortener-using-clond-services-frontend.mdx
> +I chose these products to build a frontend because of their simplicity. It's easier to build frontend apps today because React/Next Vue/Nuxt frameworks exist with es6 features compatibility in the br
Maybe at the end add what has changed now. You dont need to write boilerplate content anymore? Or why is it easier now? One sentence would be enough.

2022-03-25 13:59 UTC, vinckr commented on src/markdown/blog/building-url-shortener-using-clond-services-frontend.mdx
> +We will use the following parts of nuxt framework
```suggestion
We will use the following parts of the NuxtJS framework:
```

2022-03-25 13:59 UTC, vinckr commented on src/markdown/blog/building-url-shortener-using-clond-services-frontend.mdx
> +
Maybe describe shortly what is the end result. 

The backend is like this API + kratos etc. - maybe a small diagram could also illustrate it easier. 

And then a short description of the frontend, what does it do? a screenshot could also illustrate this part.

so the readers can get the context from last blogpost (what did we build there, how does it look and how does it connect to what we build now) as a high level overview before we actually dive in what we use and start building it.

2022-03-25 13:59 UTC, vinckr commented on src/markdown/blog/building-url-shortener-using-clond-services-frontend.mdx
> +
In the end show some commands to run the example locally.

2022-03-25 13:59 UTC, vinckr commented on src/markdown/blog/building-url-shortener-using-clond-services-frontend.mdx
> +- Add more pages with analytical information (Views/Top Referals/Highcharts.js graphs)
Good next step would also be: 
go to production with free tier
- use ory cloud instance, supabase, vercel/netlify for frontend,...

2022-04-07 13:55 UTC, vinckr requested changes
Can you add instructions how to run this with Ory Cloud (playground)? 

And at the end, instructions how to run everything locally with the backend example, so 
- clone/copy backend
- run backend like so "go run.."
- run kratos like so (cloud like this, ory proxy... / local kratos with a slightly modified docker-compose from quickstart?)
- run frontend like so
- go to localhost:3000 and test 

For the cloud version you need
npm i @ory/client
would be good if the local kratos version also uses it 🤔

2022-04-07 13:55 UTC, vinckr commented on src/markdown/blog/tutorial-url-shortener-supabase-ory-integration-frontend.mdx
> +We will use the default layout created by [create-nuxt-app](https://github.com/nuxt/create-nuxt-app). The code of `layouts/default.vue` is simple. I took the basic example of URl shotener frontend fr
Add start information here (mkdir shorts?), basically we want all the commands you need to run in the tutorial to have this example ready to go at the end.

I think i created it like this, you could also use a screenshot from your CLI maybe:
```
npx create-nuxt-app frontend

name: shorts
language: Typescript
pmanager: npm
UI framework: tailwind css
nuxt modules: axios
linting: eslint
testing: none (can do later)
rendering mode: universal
deployment: server
dev tools: jsconfig
```

2022-04-07 13:55 UTC, vinckr commented on src/markdown/blog/tutorial-url-shortener-supabase-ory-integration-frontend.mdx
> +Two parts needs to mention in this example
This could use some more detail, you can also provide some links to read more if they exist.

2022-04-07 13:55 UTC, vinckr commented on src/markdown/blog/tutorial-url-shortener-supabase-ory-integration-frontend.mdx
> +- Usage of `computed` properties that uses store feature of nuxt framework
Is this related to the code above? store.state.session.? Why do we need it how does it work?

2022-04-07 13:55 UTC, vinckr commented on src/markdown/blog/tutorial-url-shortener-supabase-ory-integration-frontend.mdx
> +- `$config` variable that needs to be updated
Where is $config, why does it need updating and what does it do?
Assume the reader does not know much about Vue.

2022-04-07 13:55 UTC, vinckr commented on src/markdown/blog/tutorial-url-shortener-supabase-ory-integration-frontend.mdx
> +Also, nuxt uses [publicRuntimeConfig](https://nuxtjs.org/docs/configuration-glossary/configuration-runtime-config/) object for application configuration using environment variables, hence we need to
maybe add that you need to add it to modules

2022-04-07 13:55 UTC, vinckr commented on src/markdown/blog/tutorial-url-shortener-supabase-ory-integration-frontend.mdx
> +<CodeFromRemote
mention this needs to be added to pages/index.vue its not clear in the rendered version

2022-04-07 13:55 UTC, vinckr commented on src/markdown/blog/tutorial-url-shortener-supabase-ory-integration-frontend.mdx
> +<CodeFromRemote
see above, mention this is in components/URLView.vue

2022-04-12 13:02 UTC, gen1us2k commented on src/markdown/blog/tutorial-url-shortener-supabase-ory-integration-frontend.mdx
> +- Usage of `computed` properties that uses store feature of nuxt framework
is it better now?

2022-04-12 13:05 UTC, gen1us2k commented
>Can you add instructions how to run this with Ory Cloud (playground)?

I think I'll add another blog post with the Ory cloud-specific changes because they're many.
I think that I'll create a guide on how to deploy it using free tiers of Ory Cloud/Vercel/Supabase and AWS with some additional notes about further steps 

There's one reason that it requires changes to the code and logic because I use oathkeeper a lot and this requires additional changes right now

2022-04-20 16:59 UTC, vinckr submitted a review, later dismissed

2022-04-21 10:43 UTC, vinckr submitted a review, later dismissed

2022-04-27 12:42 UTC, vinckr submitted a review, later dismissed

2022-04-27 13:53 UTC, aeneasr commented
Is this good fo rmerge?

2022-04-27 14:47 UTC, vinckr commented
yes, got pulled in a meeting 😅

2022-04-27 14:47 UTC, vinckr approved these changes

2022-04-27 14:47 UTC, merged