chore: review and edit
ory/web pull request #599
Opened 2022-03-18 13:42 UTC by tomekpapiernik

edit edit

2022-03-21 13:16 UTC, Benehiko requested changes
It looks good, just needs clarification on certain things, but the flow is good!

Although we want to be light and an easy read - we should also remember that we have highly technical people reading our blogs and they also need to be catered for. That why we should still keep the technical terminology and sources.

2022-03-21 13:16 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +What are sessions in technical terms? How's the data stored? Everything depends on the technology you use and the specific use case, but sessions can be stored in many different forms and formats, su
```suggestion
What are sessions in technical terms? How's the data stored? Everything depends on the technology you use and the specific use case, but sessions can be represented in many different forms and formats, such as URL query params, cookies, browser local storage, or tokens. 
```

2022-03-21 13:16 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +[VueJs](https://vuejs.org/).
```suggestion
include HTML, CSS, and JavaScript. Some popular frameworks include [React](https://reactjs.org/), [Angular](https://angular.io/), and
[VueJs](https://vuejs.org/).
```

2022-03-21 13:16 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +Server-side rendered applications aim to improve load times to guarantee a snappy user experience. They do so by rendering pages on the server before they reach the client which takes the burden of d
```suggestion
Server-side rendered applications aim to improve load times to guarantee a snappy user experience. They do so by rendering pages on the server before they reach the client which takes the burden of downloading JS assets off the browser's shoulders. Some popular frameworks used for SSR include [NextJs](https://nextjs.org/) and [NuxtJs](https://v3.nuxtjs.org/).
```

2022-03-21 13:16 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> -[OWASP Testing Cookies](https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/06-Session_Management_Testing/02-Testing_for_Cookies_Attributes).
Why is this removed?

2022-03-21 13:16 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +In the light of that risk, cookies look like a good alternative.
feels a bit flat since the emphasis on the risks are gone

2022-03-21 13:16 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +them on disk since, hopefully, your server does not restart every couple of hours. 😉
```suggestion
In such a case, tokens can easily be issued to a server and kept in memory. There's no need to store
them on disk since, hopefully, your server does not restart every couple of hours. 😉
```

2022-03-21 13:16 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> -- [OWASP Session management cheatsheet](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#session-management-implementation)
Why are sources removed?

2022-03-21 13:16 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> -- [OWASP Session management cheatsheet](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#session-management-implementation)
If the list isn't that nice we should then weave it into the text at least.

2022-03-22 09:18 UTC, tomekpapiernik commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> -- [OWASP Session management cheatsheet](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#session-management-implementation)
If you want to then yea, you can weave that into the text. 

Some of these are also repeated and pretty obvious: PWA, Angular, Vue, Electron, VueJS -> it's like you're linking to facebook.com or google.com :p

Is the main page of Vue or Angular really a source? 

Also, if you want to create a standalone "further reading list" it'd be much nicer (and acceptable for me) if you indicated what you're linking to. Maybe like this: 

```
- Read this [thread on StackOverflow](LINK) to learn more about the pros and shortcomings of cookies
- Ever wondered how to talk to a wasp? The OWASP cheatsheet has got you covered! [LINK]
- etc.
```

2022-03-22 09:19 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> -- [OWASP Session management cheatsheet](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#session-management-implementation)
yeah that makes sense! :)

2022-03-22 09:23 UTC, tomekpapiernik commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +selected.
Phew, I must've gotten distracted writing this sentence - although it makes sense there's something fishy going on here :D Your version sounds good, gonna use it.

2022-03-22 09:26 UTC, tomekpapiernik commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +## Know your ABCs
Making the tone more `fun`, maybe too much? We need a heading here, still. Let me know what you'd like to see here.

2022-03-22 09:27 UTC, tomekpapiernik commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +:::tip
Just a note from me - not sure if the blog accepts these triple-colon-triggered frames.

2022-03-22 09:38 UTC, tomekpapiernik commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +In the light of that risk, cookies look like a good alternative.
What do you consider to be `the emphasis`? You mean the formatting (bolds)?

2022-03-22 09:41 UTC, tomekpapiernik commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> -[OWASP Testing Cookies](https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/06-Session_Management_Testing/02-Testing_for_Cookies_Attributes).
Feels disconnected to me. If you're linking to something then give a good reason why you're doing that, indicate why this content is relevant for the topic. If you're not doing that then you're just 
a) cluttering the page and 
b) making the reader open new/windows tabs and forcing them to spend time judging why would they want to read the linked page instead of giving them a clear reason

2022-03-22 09:44 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +:::tip
I think they do. You can run the website locally and just test if it renders

2022-03-22 09:50 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +## Know your ABCs
I don't think it needs to be very basic or fun. I think just simply saying something informative is enough for this heading. 

```suggestion
## Auth Definitions
```


```suggestion
## Terminology
```

2022-03-22 09:53 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> -[OWASP Testing Cookies](https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/06-Session_Management_Testing/02-Testing_for_Cookies_Attributes).
Then let's add it to the end somewhere? I think it's important to have people informed by recommending good sources explicitly and not just a random link.

2022-03-22 09:55 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +In the light of that risk, cookies look like a good alternative.
bolding also this sentence is too flat imo. It feels like we didn't really give much thought to the risks since this part:

```suggestion
We do not want that responsibility on us, so hand over the responsibility to the browser by using cookies.
```

2022-03-22 09:56 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +In the light of that risk, cookies look like a good alternative.
This is the whole reason for this article. we really need to emphasise it's all about responsibility and risk

2022-03-22 09:58 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +In the light of that risk, cookies look like a good alternative.
For instance, can you use a token in the browser?

Yes! We can use a JWT or even OAuth tokens. But they aren't always the best because of
1. Your use case (why use OAuth when you have first party Authentication? or Why use a JWT when **you** need to manage it securely?)
2. Risk Mitigation and Responsibility - we don't ever want that on our plate. we would rather want the browser which is tested and patched daily to take that responsibility.

2022-03-22 10:56 UTC, tomekpapiernik commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> -[OWASP Testing Cookies](https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/06-Session_Management_Testing/02-Testing_for_Cookies_Attributes).
I'll leave that to you then, take the comments I made about the `sources` section I removed into consideration when doing that.

2022-03-22 11:05 UTC, tomekpapiernik commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +## Know your ABCs
You're really downplaying the difference the tone and language make in such posts, don't ya? :D 

`Auth Definitions` -> there's a paragraph about authn/authz and another one about sessions. Can you really say that these are both Auth Definitions?

`Terminology` -> dry and no fun but you can do that if that's your jam ;)

2022-03-22 11:06 UTC, tomekpapiernik commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +:::tip
Ok, please check before merging then.

2022-03-22 11:13 UTC, tomekpapiernik commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +In the light of that risk, cookies look like a good alternative.
> This is the whole reason for this article. we really need to emphasise it's all about responsibility and risk

Doesn't really feel like that's the whole reason for the article TBH. I felt like the post was supposed to educate on different approaches to implementing auth and how they work in different app architectures. Of course, this ultimately leads to choosing the best and most secure solution. Still, the `offloading responsibility` aspect doesn't stand out as the main point of this entire post.

2022-03-22 11:19 UTC, tomekpapiernik commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> +In the light of that risk, cookies look like a good alternative.
I commited a new version of this sentence, hope you like it!

2022-03-22 13:20 UTC, Benehiko commented on src/markdown/blog/navigating-authentication-in-modern-software-stacks.mdx
> -[OWASP Testing Cookies](https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/06-Session_Management_Testing/02-Testing_for_Cookies_Attributes).
nice! yeah i think that's a lot better

2022-03-22 14:12 UTC, Benehiko approved these changes
Looks good, I will add the OWASP sources and recommendations at the bottom as a footnote or something

2022-03-22 14:12 UTC, merged