fix: student sharing platform blogpost
ory/web pull request #620
Opened 2022-04-13 12:10 UTC by vinckr

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-04-19 11:16 UTC, vinckr commented
Hello @peteole, 
do you want to take a look before we merge it into our blog? 

https://6256f1366ef37735d9d659d8--wonderful-sinoussi-8532a7.netlify.app/student-sharing-platform-open-source-auth/

2022-04-19 11:33 UTC, peteole commented
Looks good except

1. There's something messed up with a comment in the code about Apollo Links
2. I sometimes talk about things I found strange when deploying Kratos such as the helmfile sync command not applying the new config and some other hacks. Do you just want to publish it like this on the blog? Or do you have a nice idea how to solve the issues that should be mentioned?

2022-04-25 15:36 UTC, peteole commented
Now it looks nice except that the part with the ory js sdk is not syntax highlighted

2022-04-25 16:51 UTC, vinckr commented
Yea I couldn't figure out why, but will have another go at it this week. 
I also reached out to our "kubernetes understanders" for your issue mentioned in the article, maybe we can find a good solution and include it  :-).

2022-04-28 08:57 UTC, gen1us2k commented on src/markdown/blog/student-sharing-platform-open-source-auth.mdx
> +1. Even though we correctly set the base URL in the Ory Kratos config, we need
That's not a hacky configuration because you need to deal with URL rewrites in real-life configurations. As a solution, you can move Ory Kratos to a subdomain, like https://kratos.huddle... in that case, you'll proxy traffic from the route path of the subdomain to the root path of Kratos. On the other hand, you can leave it as is.

2022-04-28 08:57 UTC, gen1us2k commented on src/markdown/blog/student-sharing-platform-open-source-auth.mdx
> +2. I was unable to find a way to put the Ory Kratos config in its own file
AFAIK `kratos.config` property is the correct way to pass kratos.config file using helm charts.

2022-04-30 08:05 UTC, peteole commented on src/markdown/blog/student-sharing-platform-open-source-auth.mdx
> +1. Even though we correctly set the base URL in the Ory Kratos config, we need
You are right, it's not that bad, I just think it's such a common issue that I would have expected the option to specify a base path in the kratos config, but I guess it's a matter of personal preferences.

2022-04-30 08:08 UTC, peteole commented on src/markdown/blog/student-sharing-platform-open-source-auth.mdx
> +2. I was unable to find a way to put the Ory Kratos config in its own file
You are right again, it would only have been nice if someone knew some helm magic that allows to move the kratos config in its own file and template it to the kratos.config field. Like this there would be proper intellisense for the config fields.

2022-04-30 08:09 UTC, peteole commented
@vinckr I'm fine with it :)

2022-05-02 18:46 UTC, peteole commented
Also the `kratos not applying config with helm upgrade`-issue has been solved here:
https://github.com/ory/k8s/pull/415

2022-05-06 13:35 UTC, vinckr commented
Made some final edits, now it is good to go IMO 💪 . 

We use this for Kubernetes secretes AFAIK @peteole:
https://github.com/bitnami-labs/sealed-secrets
Keep us in the loop on the OAuth2 server project at TUM, would love to follow that a bit.

2022-05-10 08:27 UTC, Benehiko requested changes
Nice article :) 
Just some minor things and then it should be good to go

2022-05-10 08:27 UTC, Benehiko commented on src/markdown/blog/student-sharing-platform-open-source-auth.mdx
> +follows:
not sure what you mean here. I understand the first paragraph, but the conclusion doesn't make sense. We could have sub domains here if we wanted to - as long as we are on the same TLD the cookies will be set correctly. We could even do something like our app is on `https://huddle.hsg...` while Ory Kratos is on `https://kratos.hsg.fs.tum.de`. They don't need to be separated by paths.

An who are _they_? The first paragraph is talking about Ory Developers, while the second is talking about the developers implementing Ory?

2022-05-10 08:27 UTC, Benehiko commented on src/markdown/blog/student-sharing-platform-open-source-auth.mdx
> +to install it in a cluster more or less conveniently. The interesting part here
```suggestion
to install it in a cluster. The interesting part here
```

Sounds a bit like it wasn't convenient :)

2022-05-10 08:27 UTC, Benehiko commented on src/markdown/blog/student-sharing-platform-open-source-auth.mdx
> +Is there a nicer way to handle the CSRF token? This feels a bit hacky...
```suggestion
```

Doesn't seem relevant to the article?

2022-05-10 08:27 UTC, Benehiko commented on src/markdown/blog/student-sharing-platform-open-source-auth.mdx
> +on what we could do more elegantly! Also I'm interested in yoursolutions for
```suggestion
on what we could do more elegantly! Also I'm interested in your solutions for
```

2022-05-10 08:54 UTC, gen1us2k commented on src/markdown/blog/student-sharing-platform-open-source-auth.mdx
> +follows:
The same thing for me since Kratos feels fine in multi-subdomain environments.

2022-05-10 14:34 UTC, jfcurran submitted a review, later dismissed
this is so cool

2022-05-10 22:24 UTC, vinckr commented on src/markdown/blog/student-sharing-platform-open-source-auth.mdx
> +follows:
> The problem Ory developers needed to solve here is to send some _token_ from the
> recovery link back to Ory Kratos (to verify the email) and at the same time
> associate it with a session of the UI in a web browser so that the user can
> reset their password in the UI

So what do you think when we say here it is solved (i would say "by Ory Kratos") by using browser redirects (plus with built-in security) 
and maybe link to the [multitenancy document](https://www.ory.sh/docs/kratos/guides/multi-tenancy-multitenant) @Benehiko ?

2022-05-12 15:41 UTC, Benehiko approved these changes
nice :fire:

2022-05-16 09:23 UTC, merged