fix: add CLI steps to blogpost + small edits
ory/web pull request #637
Opened 2022-05-03 14:43 UTC by vinckr

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-05-03 14:50 UTC, vinckr commented
I added some basic CLI commands, wdyt?

2022-05-03 15:29 UTC, aeneasr commented on src/markdown/blog/kratos-react.mdx
> +ory auth
Maybe add how to install the Ory CLI directly here?

2022-05-03 16:11 UTC, vinckr commented on src/markdown/blog/kratos-react.mdx
> +ory auth
you mean the brew command ? i guess most ppl use macOs, i linked the [general install doc](https://www.ory.sh/docs/guides/cli/installation) just above

2022-05-03 20:43 UTC, aeneasr commented on src/markdown/blog/kratos-react.mdx
> +ory auth
bash curl works everywhere except windows, or if on windows, it works if you use WSL. maybe we can use that method? and add a short comment?

2022-05-04 12:19 UTC, aeneasr commented on src/markdown/blog/kratos-react.mdx
> +ory create project
This also works, but it is more "magic" and requires bash and `jq` installed

```
your_project_slug=$(ory create project --name test --format json | jq -r '.slug')
export ORY_SDK_URL=https://$your_project_slug.projects.oryapis.com
```

2022-05-04 12:23 UTC, aeneasr requested changes

2022-05-04 12:23 UTC, aeneasr commented on src/markdown/blog/kratos-react.mdx
> +export ORY_SDK_URL=https://playground.projects.oryapis.com/
Use the user's project instead of playground?

2022-05-04 12:23 UTC, aeneasr commented on src/markdown/blog/kratos-react.mdx
> -export ORY_KRATOS_URL=http://localhost:4455/
Removed on purpose? Shuoldn't this be:

```
ORY_SDK_URL=http://localhost:4455/
```

2022-05-04 13:31 UTC, vinckr commented on src/markdown/blog/kratos-react.mdx
> +ory create project
cool I will include this in the CLI blogpost 👍 ! I think its too much to explain for here

2022-05-04 13:34 UTC, vinckr commented on src/markdown/blog/kratos-react.mdx
> -export ORY_KRATOS_URL=http://localhost:4455/
Thanks yea. 
Btw is it OK that i moved everything to ORY_SDK_URL. I tried it out and does not make a difference it seems.

2022-05-08 13:21 UTC, aeneasr commented on src/markdown/blog/kratos-react.mdx
> +ory create project --name <your-project-name>
Since the Ory binary is available in the currently checked out repository, you will need to do:
```suggestion
./ory auth
// Log into an existing account or create a new one
./ory create project --name <your-project-name>
```

for this to work :)

2022-05-08 13:21 UTC, aeneasr commented on src/markdown/blog/kratos-react.mdx
> +export ORY_SDK_URL=https://yourproject-slug-0000000000.projects.oryapis.com
If you make it one sentence it's easier to select/remove using keyboard shortcuts :)

```suggestion
export ORY_SDK_URL=https://YOUR_PROJECT_SLUG_HERE.projects.oryapis.com
```

2022-05-08 15:37 UTC, aeneasr requested changes

2022-05-08 15:37 UTC, aeneasr commented on src/markdown/blog/kratos-react-custom-ui.mdx
> +````
Fix the backticks

2022-05-08 15:37 UTC, aeneasr commented on src/markdown/blog/kratos-react-custom-ui.mdx
> +````
Fix the backticks

2022-05-08 15:37 UTC, aeneasr commented on src/markdown/blog/kratos-react-custom-ui.mdx
> +bash <(curl https://raw.githubusercontent.com/ory/meta/master/install.sh) -b . ory
Please apply the suggestions from the other PR here as well

2022-05-08 15:37 UTC, aeneasr commented on src/markdown/blog/kratos-react-custom-ui.mdx
> +// Create a new project
Similar to my proposed changes in the other document, can you add this here too?

2022-05-09 09:36 UTC, vinckr commented
Thanks I addressed your comments and looks good now IMO.

2022-05-09 09:36 UTC, vinckr commented on src/markdown/blog/kratos-react.mdx
>    />
lets go!

2022-05-09 10:09 UTC, aeneasr commented on src/markdown/blog/kratos-react-custom-ui.mdx
> +// Create a new project
Please see https://6278dddf762cc10b3d450307--wonderful-sinoussi-8532a7.netlify.app/login-spa-react-nextjs-authentication-example-api-open-source/#ory-kratos-on-your-machine

This is not yet addressed. We should explicitly explain how to set up the environment variable correctly for both cloud, and kratos (even though it's kind of a duplicate):

<img width="1131" alt="Screenshot 2022-05-09 at 12 05 33" src="https://user-images.githubusercontent.com/3372410/167388276-42af0a59-f07d-41ed-8d33-61a5784ed943.png">

ps: the best way to address someone's PR review is to also look at the changes they have made. That can be done by clicking on the commits from the other person:

https://github.com/ory/web/pull/637/files/807859f42f5ac094842d8c8d5ed17890c5893364..4af621328a87bf2b148d4e5588fbf56acad2d049

or filtering them in the files view:

<img width="717" alt="Screenshot 2022-05-09 at 12 07 28" src="https://user-images.githubusercontent.com/3372410/167388642-0c350cf6-ef26-4454-918e-c1d3d8d8c0c0.png">

Often, reviewers will do part of your task to communicate what they need. It's often easier than adding 100 comments.

2022-05-09 10:10 UTC, aeneasr commented on src/markdown/blog/kratos-react-custom-ui.mdx
> +// Create a new project
In general, the purpose of making changes directly to a PR as a maintainer is to show by example, rather than try to explain what they mean. Reviewing changes from a maintainer on one's self PR is often very teaching as you learn about code styles, preferences, ideas, and ways of programming

2022-05-09 12:01 UTC, vinckr commented on src/markdown/blog/kratos-react-custom-ui.mdx
> +// Create a new project
Thanks, the examples do help a lot and the commit view in files is also helpful, I  missed one commit of yours before and thus misunderstood your comment.

Should be all there now.

2022-05-09 14:45 UTC, aeneasr approved these changes

2022-05-09 14:50 UTC, merged