feat: CLI Landing page content
ory/web pull request #649
Opened 2022-05-19 16:30 UTC by DaydreamerUnicorn

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-05-20 06:39 UTC, BlueAcidFrog commented
@DaydreamerUnicorn not sure what the changes are on this. I suggest we go over this together.

2022-05-20 14:23 UTC, BlueAcidFrog commented on src/page-content/content-cli.tsx
> +      to: '/guides/cli/installation'
```suggestion
      to: '/guides/cli/installation'
```

2022-05-20 14:31 UTC, BlueAcidFrog requested changes
@DaydreamerUnicorn good in the meta description and SEO. Please review my comments - Thx

2022-05-20 14:31 UTC, BlueAcidFrog commented on src/page-content/content-cli.tsx
> +      to: '/guides/cli/installation'
This link does not work

2022-05-20 14:31 UTC, BlueAcidFrog commented on src/page-content/content-cli.tsx
> +  id: 'kratos.hero',
```suggestion
  id: 'kratos.hero',
```

2022-05-20 14:31 UTC, BlueAcidFrog commented on src/page-content/content-cli.tsx
> +  id: 'kratos.hero',
The image does not fit in with CLI

2022-05-20 14:31 UTC, BlueAcidFrog commented on src/page-content/content-cli.tsx
> +           Install Ory and Run it. Now sit back and relax while the CLI got it.
```suggestion
           Install Ory and run it. Now sit back and relax while the CLI got it. 
```

2022-05-20 14:31 UTC, BlueAcidFrog commented on src/page-content/content-cli.tsx
> +            Ory CLI works like no other. Just install and let it work the magic.
```suggestion
            Ory CLI works like no other. Just install and let it work the magic.
```

2022-05-20 14:31 UTC, BlueAcidFrog commented on src/page-content/content-cli.tsx
> +            Ory CLI works like no other. Just install and let it work the magic.
This needs more substance. If there is no value to communicate we should not write something for the purpose of writing - be specific and precise

2022-05-20 14:31 UTC, BlueAcidFrog commented on src/page-content/content-cli.tsx
> +           Install Ory and Run it. Now sit back and relax while the CLI got it.
same as above

2022-05-20 14:31 UTC, BlueAcidFrog commented on src/page-content/content-cli.tsx
> +      src={Kratos}
Does that not require to be changed as well?

2022-05-20 15:00 UTC, BlueAcidFrog commented
can you please add this part as well? 

Fast and Simple Use of CLI in Just 4 Steps

1. Install the Ory CLI
2. Save a file in Git (for example mfa: disabled)
3. See the changes made (who, what, and when) (For example John Doe enabled the MFA at 12:00 PM)
4. Write that in a file and let the CLI process it

And that’s it!

2022-05-20 15:49 UTC, DaydreamerUnicorn commented
@vinckr, can you please edit the 'Kratos' bits in the VS code from the CLI landing page tonight?

2022-05-23 07:58 UTC, RinorG commented on src/page-content/content-cli.tsx
> +      to: '/guides/cli/installation'
where should it lead to?

2022-05-23 07:58 UTC, RinorG commented on src/page-content/content-cli.tsx
> +  id: 'kratos.hero',
Out of all alternatives currently in project, i think it's the best.

2022-05-23 17:22 UTC, DaydreamerUnicorn commented
@jfcurran, please see that the icons need to be changed for the 'Fast and simple use of CLI' part.

2022-05-24 08:22 UTC, DaydreamerUnicorn commented on src/page-content/content-cli.tsx
> +            <> Use CLIs simplified commands to process a file or a project until you know you're done.
Please edit **CLIs** to **CLI's**

2022-05-24 10:25 UTC, jfcurran commented
please resolve the few changes that @BlueAcidFrog requested.

2022-05-24 15:31 UTC, jfcurran approved these changes
Some wording is repetitive, but this works

2022-05-24 15:37 UTC, merged