Adding Social sign in feature + banner about permission (Keto) to cli page
ory/web pull request #656
Opened 2022-05-25 09:30 UTC by BlueAcidFrog

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-05-25 11:17 UTC, BlueAcidFrog commented
@RinorG we need to change images

2022-05-27 13:05 UTC, RinorG commented
@vinckr pls review :)

2022-05-27 16:24 UTC, vinckr commented on src/page-content/content-social-signin.tsx
> +  title: 'Increase registrations with Ory Social Sign-in'
```suggestion
  title: 'Increase registrations with Ory Social Sign-in',
```

2022-05-27 16:27 UTC, vinckr commented
Please make sure the build succeeds and mark ready for review 🙏 . the run logs should give a good hint as to what is wrong/making the build fail https://github.com/ory/web/runs/6625290835?check_suite_focus=true

2022-05-30 09:35 UTC, RinorG commented
It says that all checks have passed for me @vinckr

2022-05-30 12:09 UTC, DaydreamerUnicorn commented
@jfcurran, please review and merge. Thanks!

2022-05-30 13:17 UTC, vinckr commented
> It says that all checks have passed for me @vinckr

Yea, I fixed it in https://github.com/ory/web/pull/656/commits/655d60851c17fe45a1afd83836bee11cd754a317, just for the future :)

2022-05-30 13:20 UTC, vinckr requested changes
Looks quite, good I have some ideas how it can be improved further.

2022-05-30 13:20 UTC, vinckr commented on src/page-content/content-social-signin.tsx
> +              Ory deviates from account linking as this method poses a critical security threat to users of your website or app.
>Safety from the dangers of account linking

lets remove this, its confusing and not really a feature anyway.

2022-05-30 13:20 UTC, vinckr commented on src/page-content/content-social-signin.tsx
> +    'Add social logins into your website or app. Welcome great user experience. Install Ory Social Sign-in to make your users feel at ease.',
"Welcome great user experience" is not really a sentence?
I guess in the SEO props its not that important, but this still sounds strange IMO.

2022-05-30 14:13 UTC, DaydreamerUnicorn commented on src/page-content/content-social-signin.tsx
> +              Ory Cloud gives you convenient and GUI-friendly flows to add the social network logins. Each flow is created to suit the requirements of a particular platform.
It could've been 'custom-tailored flow' as  mentioned in the documentation. We can replace it with  another term, if you can suggest any.

2022-05-30 14:24 UTC, DaydreamerUnicorn commented on src/page-content/navigation/header.json
> +          "description": "Planet scale standards",
It needs to be fixed.

2022-05-30 14:27 UTC, DaydreamerUnicorn commented on src/page-content/content-social-signin.tsx
> +    'Add social logins into your website or app. Welcome great user experience. Install Ory Social Sign-in to make your users feel at ease.',
It's a sentence, yes. It shows on the SERPs, and is a good way to let people know how this solution solves their problem. We can alter the text a bit, to make it look more appropriate. Do you have any suggestions?

2022-05-30 14:31 UTC, DaydreamerUnicorn commented on src/pages/social-signin.tsx
> +    <FeatureList {...content.featureList} />
Sure, makes sense.

Which description are we talking about here?

2022-05-31 11:56 UTC, vinckr commented on src/page-content/content-social-signin.tsx
> +              OAuth 2.0 and OpenID Connect are the power mechanisms for social logins. Ory makes sure to keep permissions and authentication confidential at all times.
>replace 'power mechanism' to 'frameworks'.

SGTM!

>Ory makes sure to keep social logins a matter of consistent convenience.

not sure if I understand this one - you want to express that is is convenient for the end-user to use social logins?

2022-05-31 11:57 UTC, vinckr commented on src/page-content/content-social-signin.tsx
> +              Ory deviates from account linking as this method poses a critical security threat to users of your website or app.
Hm its rather you can use account linking with social sign-in, even with Ory! 

But we strongly discourage it since it is very unsafe.

2022-05-31 12:01 UTC, vinckr commented on src/page-content/content-social-signin.tsx
> +              Ory Cloud gives you convenient and GUI-friendly flows to add the social network logins. Each flow is created to suit the requirements of a particular platform.
Oh ok, from the headline I understood it as each social login provider has a custom flow - but for the end-user the flow is always the same!

2022-05-31 12:02 UTC, vinckr commented on src/page-content/content-social-signin.tsx
> +    'Add social logins into your website or app. Welcome great user experience. Install Ory Social Sign-in to make your users feel at ease.',
Fair enough 😉 We can also use it like this. 

Or what do you think of:
"Add great user experience with social logins into your website or app."

2022-05-31 12:05 UTC, vinckr commented on src/pages/social-signin.tsx
> +    <FeatureList {...content.featureList} />
I meant the content of "usageList"; so the description how social logins works under the hood. 

![Uploading Screenshot 2022-05-31 at 14.04.41.png…]()

This should only be interesting/relevant to developers, right?

2022-05-31 12:05 UTC, vinckr submitted a review, later dismissed
I left some comments to clarify my previous review.

2022-05-31 12:12 UTC, BlueAcidFrog commented
@DaydreamerUnicorn please review the comments to get this live today :)

2022-06-01 15:05 UTC, aeneasr commented on src/page-content/content-social-signin.tsx
> +  title: 'Increase registrations with Ory Social Sign-in',
👍

2022-06-01 15:11 UTC, DaydreamerUnicorn submitted a review, later dismissed

2022-06-02 14:57 UTC, jfcurran approved these changes

2022-06-02 15:25 UTC, merged