Mfa landingpage
ory/web pull request #668
Opened 2022-06-01 16:28 UTC by DaydreamerUnicorn

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-06-09 09:31 UTC, RinorG commented
@jfcurran @vinckr this is ready for a merge right?

2022-06-09 12:09 UTC, vinckr requested changes
Looks pretty good, I noticed some things in the text that stood out and should be addressed before merging.

2022-06-09 12:09 UTC, vinckr commented on src/page-content/navigation/header.json
> +          "description": "MFA",
```suggestion
          "description": "Based on proven standards",
```

This is just a suggestion, but can we find something more expressive than "MFA" ?

2022-06-09 12:09 UTC, vinckr commented on src/page-content/content-mfa.tsx
> +            Introducing rigorous security with{' '}
```suggestion
            Introduce rigorous security with{' '}
```


I think its always better to use the simple form in heros and CTAs, it directly speaks to the reader (introduce this to make X)

2022-06-09 12:09 UTC, vinckr commented on src/page-content/content-mfa.tsx
> +                    ),
Since the audience is less technical for this page, maybe it would make sense to also mention what you can do with that,

this is also mentioned in the [documentation](https://www.ory.sh/docs/kratos/concepts/credentials/webauthn):

- a USB, NFC, or Bluetooth low energy device (e.g. [YubiKey](https://www.yubico.com/)) to authenticate;
- (e.g. TouchID, FaceID, Windows Hello Face, Android Biometric Authentication, ...);

2022-06-09 12:09 UTC, vinckr commented on src/page-content/content-mfa.tsx
> +                            Configure MFA using Ory CLI or even self-hosted projects.
```suggestion
                            Configure MFA using the Ory CLI.
```

Should we explicitly mention self-hosting in the Cloud product pages?

2022-06-09 12:35 UTC, DaydreamerUnicorn commented on src/page-content/content-mfa.tsx
> +                            Configure MFA using Ory CLI or even self-hosted projects.
I think the motive behind mentioning it to increase signups and also to pave way for conversions. I hope that makes sense, since CLI has its own landing page.

2022-06-09 13:24 UTC, vinckr commented on src/page-content/content-mfa.tsx
> +                            Configure MFA using Ory CLI or even self-hosted projects.
That makes sense but why mention self-hosted projects? The landing page is for the managed Ory Cloud right?

2022-06-09 13:24 UTC, vinckr commented on src/page-content/navigation/header.json
> +          "description": "MFA",
>Secure login and authentication

this I like the best, committing it now, but feel free to change if you find something better.

2022-06-09 14:05 UTC, DaydreamerUnicorn commented on src/page-content/content-mfa.tsx
> +                    ),
Can you please elaborate a bit more?

2022-06-09 14:08 UTC, DaydreamerUnicorn commented on src/page-content/navigation/header.json
> +          "description": "MFA",
Cool. Looks good there!

2022-06-10 14:35 UTC, jfcurran approved these changes
@DaydreamerUnicorn Please have a look at the changes I made and approve them or make suggestions for changes. 

As an aside, its important we add new content Items to the `footer.json` as well as to the `header.json`

2022-06-13 09:10 UTC, jfcurran commented
@BlueAcidFrog not currently, one could be added at a later time

2022-06-13 09:10 UTC, jfcurran approved these changes
great stuff @RinorG 😎

2022-06-17 09:43 UTC, merged