blog: dockertest covid article
ory/web pull request #85
Opened 2020-11-27 12:22 UTC by vinckr

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added necessary documentation within the code base (if
      appropriate).

2020-11-27 12:38 UTC, zepatrik reviewed
Just some small comments, I will read it thoroughly later.

2020-11-27 12:38 UTC, zepatrik commented on src/pages/blog/ory-vs-covid.md
> + How Open-source software and Ory can be part of a greater effort against the virus
This was removed recently, adapt according to the other PRs :wink:

2020-11-27 12:38 UTC, zepatrik commented on src/pages/blog/ory-vs-covid.md
> +```
```suggestion
```go
```

2020-11-27 12:38 UTC, zepatrik commented on src/pages/blog/ory-vs-covid.md
> +```
Or if the code is copied from GH, use https://github.com/ory/web/pull/75/files#diff-9cdb5dd0b1f36dc0efaf706b88cb1744be3b404f4095e8c4e384b51cd046ba94R128-R132

2020-11-27 12:38 UTC, zepatrik commented on src/pages/blog/ory-vs-covid.md
> +
```suggestion
```

2020-11-27 12:43 UTC, zepatrik commented on src/pages/blog/ory-vs-covid.md
> + NewTestDatabaseWithConfig creates a new database suitable for use in testing.
```suggestion
// NewTestDatabaseWithConfig creates a new database suitable for use in testing.
```

2020-11-27 13:35 UTC, vinckr commented
It is now Ory Dockertest throughout the article. 
There could be some improvements to the headline/teaser and keywords.

2020-11-27 14:10 UTC, aeneasr requested changes

2020-11-27 14:10 UTC, aeneasr commented on src/pages/blog/ory-vs-covid.md
> +### What is Ory Dockertest?
Do not start posts directly with a headline or this happens:

<img width="1207" alt="Bildschirmfoto 2020-11-27 um 15 08 18" src="https://user-images.githubusercontent.com/3372410/100457499-6e76cc00-30c2-11eb-83c4-5e4471bbcf7d.png">

2020-11-27 14:10 UTC, aeneasr commented on src/pages/blog/ory-vs-covid.md
> +### How Dockertest is helping keeping Covid in check
This post has no H2 (`##`). Make sure to keep the structure of h2,h3,h4,h5, ...

https://yoast.com/how-to-use-headings-on-your-site/

2020-12-01 19:02 UTC, aeneasr commented
ready for merge?

2020-12-01 19:12 UTC, vinckr commented
@aeneasr Headlines should be good now. 
Jared also gave his ok to publish. 👍

2020-12-02 11:21 UTC, aeneasr requested changes
Please replace all `Ory` with `ORY`. Replacing the naming is a concerted effort across all resources and needs to be done all at once.

2020-12-02 11:21 UTC, aeneasr commented on src/pages/blog/ory-vs-covid.md
> +path: '/ory-vs-covid/'
```suggestion
path: '/dockertest-gaen-google-apple-exposure-notification-covid-19/'
```

2020-12-02 11:21 UTC, aeneasr commented on src/pages/blog/ory-vs-covid.md
> +    Open source software critical for global virus response
```suggestion
    Write tests like Google and Apple Exposure Notifications using Dockertest
```

2020-12-02 11:21 UTC, aeneasr commented on src/pages/blog/ory-vs-covid.md
> +  How Ory is helping keep Covid in check
```suggestion
  Keeping Covid-19 in check with ORY Dockertest
```

2020-12-02 14:20 UTC, vinckr commented
Ok changed it. 
The filename is correct like this?

2020-12-02 14:28 UTC, aeneasr commented on src/pages/blog/dockertest-gaen-google-apple-exposure-notification-covid-19.md
> +Should you have further questions or feedback, visit the [ORY community forum](https://community.ORY.sh/) or [chat](https://www.ORY.sh/chat).
Not the domain names...

2020-12-02 14:36 UTC, aeneasr requested changes

2020-12-02 14:36 UTC, aeneasr commented on src/pages/blog/dockertest-gaen-google-apple-exposure-notification-covid-19.md
> +[Dockertest](https://github.com/ORY/Dockertest) automates your interactions with the Docker API. This lets you test your services database integration in a simple and straightforward way.
Please be more careful when using cmd+replace. This should not have been replaced.

2020-12-02 14:36 UTC, aeneasr commented on src/pages/blog/dockertest-gaen-google-apple-exposure-notification-covid-19.md
> +You can find examples for all common databases on [github.com/ORY/Dockertest](https://github.com/ORY/Dockertest).
same

2020-12-02 14:36 UTC, aeneasr commented on src/pages/blog/dockertest-gaen-google-apple-exposure-notification-covid-19.md
> +In [Dockertest](https://github.com/ORY/Dockertest) a pool represents a connection to the Docker API and is used to handle docker images and resources represent the docker containers.
same

2020-12-02 14:36 UTC, aeneasr commented on src/pages/blog/dockertest-gaen-google-apple-exposure-notification-covid-19.md
> +Now what does this have to do with [Dockertest](https://github.com/ORY/Dockertest)?
same

2020-12-02 14:36 UTC, aeneasr commented on src/pages/blog/dockertest-gaen-google-apple-exposure-notification-covid-19.md
> +It is amazing to see a tool that was written to ease the development process at ORY is used by big tech organisations in the most impactful health operation in modern times. It shows what a reliable
same

2020-12-02 14:36 UTC, aeneasr commented on src/pages/blog/dockertest-gaen-google-apple-exposure-notification-covid-19.md
> +The whole GAEN project is open-source, as is [Dockertest](https://github.com/ORY/Dockertest). The whole concept of contact tracing or exposure notification works great with open source, since it cuts
same

2020-12-02 14:36 UTC, aeneasr commented on src/pages/blog/dockertest-gaen-google-apple-exposure-notification-covid-19.md
> +Thanks for taking the time to read this article! Check out (our blog)[https://www.ORY.sh/blog] for more articles and tutorials.
same

2020-12-02 14:36 UTC, aeneasr commented on src/pages/blog/dockertest-gaen-google-apple-exposure-notification-covid-19.md
> +[Dockertest](https://github.com/ORY/Dockertest) is just one example of how ORY approaches advanced software development for cloud native applications.
same

2020-12-02 14:36 UTC, aeneasr commented on src/pages/blog/dockertest-gaen-google-apple-exposure-notification-covid-19.md
> +Sign up to [the ORY newsletter](https://ORY.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53) and we will notify you of new updates to [ORY Dockertest](https://github.com/ORY/
same

2020-12-02 14:36 UTC, aeneasr commented on src/pages/blog/dockertest-gaen-google-apple-exposure-notification-covid-19.md
> +Should you have further questions or feedback, visit the [ORY community forum](https://community.ORY.sh/) or [chat](https://www.ORY.sh/chat).
```suggestion
Should you have further questions or feedback, visit the [ORY Community Forum](https://community.ory.sh/) or [ORY Slack](https://www.ory.sh/chat).
```

2020-12-03 10:12 UTC, vinckr commented on src/pages/blog/dockertest-gaen-google-apple-exposure-notification-covid-19.md
> +[Dockertest](https://github.com/ORY/Dockertest) automates your interactions with the Docker API. This lets you test your services database integration in a simple and straightforward way.
Ok! 
I thought capitalization wouldnt matter in the URL.

2020-12-03 10:20 UTC, aeneasr approved these changes

2020-12-03 10:20 UTC, merged